### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by matswebjorn** [Isaksson/node-red-contrib-unifi#1]
If Node-RED has been installed according to the instructions on https://nodered.org/docs/getting-started/installation, then the installation command for node-red-contrib-unifi has to be done from inside the Node-RED user-directory (default $HOME/.node-red) and prefixed with sudo.

**Comment by Isaksson** [comment]
The recommended way to install this is from the Node-RED gui itself.
Meny/manage palette/Install/search for unifi and then click install.

Do you want me to add your manual instruction to the Readme?

**Comment by matswebjorn** [comment]
Yes, please update the manual instructions. And a note about installing from Node-RED could be nice (may not be obvious to all users)

BR
Mats

Från: Kristoffer Isaksson [mailto:notifications@github.com]
Skickat: den 20 augusti 2017 22:51
Till: Isaksson/node-red-contrib-unifi
Kopia: Mats Webjörn/WIKAB; Author
Ämne: Re: [Isaksson/node-red-contrib-unifi] Installation instructions (#1)


The recommended way to install this is from the Node-RED gui itself.
Meny/manage palette/Install/search for unifi and then click install.

Do you want me to add your manual instruction to the Readme?

**Comment by Isaksson** [comment]
Readme updated
