### ISSUE TITLE
Block Client  command use

### ISSUE THREAD

**Issue by jaywehner** [Isaksson/node-red-contrib-unifi#10]
Not an issue just a usage question. How are the commands sent? What node is used to send a blockClient or unblockClient? IT say's no GUI so not sure if this is a EXEC or should it be placed in a function? Any help is appreciated. Thanks

well I guess RTFM is in play here :)

Function:
msg.payload = { command: "unblockClient", mac: "FF:D4:FF:D4:FF:FF" };

**Comment by jaywehner** [comment]
This can be closed. Helpful for next person :)

**Comment by Isaksson** [comment]
Good that you found the instruction ;)

**Comment by jaywehner** [comment]
Yep. Thank you for your hard work. Works great!
