### ISSUE TITLE
Errormessage

### ISSUE THREAD

**Issue by PowerZone21** [Isaksson/node-red-contrib-unifi#100]
Hi,
I have been used this node for a while without any problems, but today I got an errormessage:
depth_zero_self_signed_cert  With a red dot, under the Unifinode
Tried to add an debug node, but this says nothing

Please help

**Comment by Isaksson** [comment]
Hello.
Do you use the latest version of this node?

**Comment by Isaksson** [comment]
Please try to "uncheck" the SSL Verification checkbox in the configuration for this node.

**Comment by PowerZone21** [comment]
Hi,

I have the lastest version and SSL are already unchecked

**Comment by PowerZone21** [comment]
I have also rebooted node-red

**Comment by Isaksson** [comment]
What Unifi Controller do you use, and what version of it?

**Comment by PowerZone21** [comment]
Dream Machine ver. 1.12.38

**Comment by Isaksson** [comment]
It seem that version was release like 6 days ago, and it bundles the UniFi Network 7.2.97
Did the issue start after that update?

**Comment by PowerZone21** [comment]
I see.
Its very posseble that this have been for some days, but I catch it today.
Would there be an solution in some days then?

**Comment by Isaksson** [comment]
What certificate do you see if you use a browser and go to the same ip address that you use for the configuration of the Unifi Node?

**Comment by PowerZone21** [comment]
![image](https://user-images.githubusercontent.com/81422450/218586756-212c2014-9ad6-41b5-beb8-928e83a19f65.png)

**Comment by Isaksson** [comment]
If you click View Certificate, please post the image of that. What I want to know if its not only self signed but maybe also expired

**Comment by Isaksson** [comment]
The only way for me to reproduce this error is to enable the "SSL Verification" if that is unchecked then it should accept event self signed certificates, could you please verify your settings again.

**Comment by PowerZone21** [comment]
![image](https://user-images.githubusercontent.com/81422450/218873213-0026b5cf-8e99-4ab6-8a78-aeed146ff4fb.png)
![image](https://user-images.githubusercontent.com/81422450/218873305-5c33147d-0830-467e-98b1-a97cb0119bae.png)
![image](https://user-images.githubusercontent.com/81422450/218873385-46c3899b-aac4-4f8c-9b30-02dde917ebbc.png)

**Comment by PowerZone21** [comment]
![image](https://user-images.githubusercontent.com/81422450/218875283-3d26a942-efa1-4baa-897a-b32b45cd48b9.png)
![image](https://user-images.githubusercontent.com/81422450/218875377-b39f48cc-f2d2-413a-8f54-9d701edb4458.png)

**Comment by PowerZone21** [comment]
Debug Node shows no info

**Comment by Isaksson** [comment]
Okey, well this one is a very odd issue.
I cant produce the same error here.
The only way for me to have a possibility to solve this for you is that you let me connect to your Dream Machine from my developer environment.
That means that you must have some basic knowledge in port forward and firewall rules, you have to create a local user in your Dream Machine and give permission to me to access your network environment over internet.

Let me know if you are interested of this and then we could sort out the details outside this forum.

**Comment by PowerZone21** [comment]
Of course I'm interrested in solve this issue.
I'm not an expert in networking, but I will give it a try.
You can sen me the details in an e-mail for example?  kes-hol@online.no
