### ISSUE TITLE
POE passthrough not supportet

### ISSUE THREAD

**Issue by maxschloegl** [Isaksson/node-red-contrib-unifi#101]
Hi!

I have a suggestion for improvement.
I have a Unifi US-8 switch. It has 8 ports, is powered via POE and port number 8 supports POE passthrough.

https://dl.ubnt.com/qsg/US-8/US-8_EN.html

With your package it is possible to deactivate POE on the port, but not to reactivate it with "enablePoePort".
For this it would be necessary that the package supports the poe_mode "passthrough".
I have tested this on my system and it works.

You would have to add "passthrough" to the following code line:
https://github.com/Isaksson/node-red-contrib-unifi/blob/f6ecaebd377c46a171282e0f09175649b4d8fbf5/unifi-helper.js#L1570

Would it be possible to include this in the official code?

Kind regards
Max

**Comment by Isaksson** [comment]
Hello.
Yeah, sure.
I will add this to next release.

Thanks for that.

**Comment by maxschloegl** [comment]
Hello. Thanks for your reply and including into the code.

**Comment by Isaksson** [comment]
Please try out the new function and get back with the result.

**Comment by maxschloegl** [comment]
> Please try out the new function and get back with the result.

Installed new version and it's working fine.
Thank you.
