### ISSUE TITLE
Feature Request - get list of traffic rules and get status of traffic rule

### ISSUE THREAD

**Issue by lensherm** [Isaksson/node-red-contrib-unifi#102]
Thank you for great work. It would be nice to be able to have a couple more commands for the traffic rules, if/when you get a chance.

1. Get the full list of traffic rules and their states. I'm able to see this by calling:
`https://x.x.x.x/proxy/network/v2/api/site/default/trafficrules/`

2. Get the current state of a specific traffic rule given its id

**Comment by Isaksson** [comment]
I will add this in the next release, I did prepare for this when I added the other function for Traffic Rules.
Thanks for the Feature Request

**Comment by lensherm** [comment]
Thanks! Much appreciated.

**Comment by Isaksson** [comment]
Please try out the new function and get back with the result.
