### ISSUE TITLE
ERR_BAD_REQUEST when using any command other than SitesStats

### ISSUE THREAD

**Issue by ghost** [Isaksson/node-red-contrib-unifi#104]
As the title states whenever I try a different command it throws the bad request error. I'm able to parse some data from SiteStats but it would be nice to be able to use the others. Also how would I execute the non gui commands? The firewall groups example does not work. I get the same bad request error.

**Comment by Isaksson** [comment]
Have you verified that you are using the correct sitename in the configuration? it should be the same name that you receive from the SitesStats command.

**Comment by ghost** [comment]
> Have you verified that you are using the correct sitename in the configuration? it should be the same name that you receive from the SitesStats command.

Yes I'm using the generated name from the SiteStats command. I'm still receiving this error. Please advise

**Comment by ghost** [comment]
Any news on this? This API does not work, I've tried everything under the sun to get this going. Please provide any advice

**Comment by ghost** [comment]
@Isaksson any assistance with this would be helpful. You didn't provide much help initially and your API isn't working with other commands

**Comment by Isaksson** [comment]
Well, I don't know what to say, this Node is working and I have tried with many different installations with success every time.
It's hard to fix something that is not broken.
Please try a new installation of Node-RED and only install this Node.

If you still have issue then, let me know the exact version of everything involved in your installation so that I could replicate that in my environment.

**Comment by jyavenard** [comment]
I'm now seeing this following update of my UDM pro.

Tried with new local node-red docker container 
<img width="699" alt="image" src="https://github.com/Isaksson/node-red-contrib-unifi/assets/505748/8d6576b6-b0c0-43d8-9403-5191d9473324">
<img width="523" alt="image" src="https://github.com/Isaksson/node-red-contrib-unifi/assets/505748/babd54c2-ac7e-4793-b1d3-ee231957d682">

Can't figure out exactly what is wrong with it unfortunately, no idea on how to debug.

**Comment by jyavenard** [comment]
running Version 7.4.162

**Comment by Isaksson** [comment]
@jyavenard I created a new issue based on your information due to this case is closed.
