### ISSUE TITLE
ClientDevices returns empty array

### ISSUE THREAD

**Issue by BRT917** [Isaksson/node-red-contrib-unifi#11]
Hi, the ClientDevices command is returning an empty array in msg.payload for me. I have verified that I am connecting and running commands successfully as the AccessDevices command returns an array containing my two AP's in msg.payload.

more info:
node-red-contrib-unifi v0.06 installed fresh from the UI, no custom commands are being sent
I am connecting to a local cloudkey with build atag_5.10.17_11638 installed

**Comment by Isaksson** [comment]
Hello. I will take a look at this and get back to you.

**Comment by Isaksson** [comment]
I have now made some test against my environment and that commands provides me with an array with devices.
My controller is atag_5.9.29_11384 I will update my controller to latest version and then I hope I could reproduce your issue.

**Comment by Isaksson** [comment]
I have now updated to latest version and the command is still working for me.
atag_5.10.17_11638
Iam including a picture of my Node settings just to make sure that it is not a simple mistake
![unifi-clientdevices](https://user-images.githubusercontent.com/4119080/52904722-5658f400-3230-11e9-87f8-683cbeec802c.PNG)

**Comment by BRT917** [comment]
Yeah mine is pretty much the same. So maybe it's an issue on my cloudkey/unifi side then. I'll investigate that further then. Here's mine config and the output I'm seeing.

![image](https://user-images.githubusercontent.com/11722857/52918107-1e8d9300-32a8-11e9-84a5-482a1e612738.png)

Thanks for taking the time to check, and for creating a very helpful utility.
