### ISSUE TITLE
UCK G2 Plus - UnifiOS - Unknown Error

### ISSUE THREAD

**Issue by ljpaff** [Isaksson/node-red-contrib-unifi#116]
Hi,

i'm using UCK G2 Plus to manage Unifi devices. I have configured plugin with UnifiOS=yes and default site. But when it request "ClientDevices", after a lot of time waiting, it responses me "Unknow error"

![image](https://github.com/Isaksson/node-red-contrib-unifi/assets/27012839/002acc15-d070-409d-a02f-d7249d81ea49)
![image](https://github.com/Isaksson/node-red-contrib-unifi/assets/27012839/233b53d4-43bd-4648-9fe5-1847b132495d)

**Comment by Isaksson** [comment]
Hello.
Could you please try to use the ip address instead of the DNS name for your Cloud Key.

**Comment by ljpaff** [comment]
No change after all

**Comment by Isaksson** [comment]
If you download the latest version then you could enable debug on that node and then upload the log file here and then I could take a look.
