### ISSUE TITLE
Change LED Color from AP

### ISSUE THREAD

**Issue by scarefirego** [Isaksson/node-red-contrib-unifi#117]
it is possible to change the led fromm AccessPoint? What is the command?

**Comment by Isaksson** [comment]
Hello, do you mean that you want turn the LED on/off or do you have AP that could change color?

**Comment by scarefirego** [comment]
i have 3 ap with rgb colors. how can i change the color not on off

Type: U6 AP

**Comment by Isaksson** [comment]
I don't have any AP with RGB so its hard to develop the function, but I checked at this page
https://eu.store.ui.com/eu/en?category=all-wifi

Do you have any of those? 
It seems like there is only white/blue LED on the APs that you could buy today.

**Comment by scarefirego** [comment]
Yes it is possible to change the color from all U6 AP, try in the app or Web-app from Unifi. In the ap-setting its a point under the LED-Switch
![IMG_9801](https://github.com/Isaksson/node-red-contrib-unifi/assets/63153849/67740be9-e3ea-4a2a-900f-f771d5b300a4)

**Comment by Isaksson** [comment]
I think its only possible on the old U6 AP, it seems like they have changed all AP to White/blue LEDs now, there was several posts about this on some forums, one user bought two AP of the same series and it was RGB on one of them and just two color on the second.

The problem is that I dont have any U6 APs only older and all of them is only dual color.

**Comment by scarefirego** [comment]
not realy its a new U6-Mesh and U6-Pro. The devices are newest from unifi. I have a old AP pro that can only change blue and white. The new generation can RGB and brightness. Firmware is up to date. Device Brand built is 02/27/23

**Comment by Isaksson** [comment]
Ahh okey, that's strange. According the documentation for the U6 Pro it only has White/blue LED
https://eu.store.ui.com/eu/en/pro/category/all-wifi/products/u6-pro

And it looks like German language in your screenshot so you have Unifi devices in the European versions?

**Comment by Isaksson** [comment]
There is two options for me to start to develop this function.
Option 1 is that you give me access to your environment so that I could debug/analyze what command to use to change the LED color, your AP will be affected with the LED change during my work.

Option 2 is that I need and AP with RGB LED donated for me (money so that I could buy one that has it) or an AP sent to me for keep or sent back when the development is done.

**Comment by scarefirego** [comment]
Yes EU Version.
I could try to adapt your code with me.
In NODE RED he sends the following in the picture.
Maybe you have an idea.
Is there a documentation of the API with all commands?
<img width="239" alt="Bildschirmfoto 2023-09-06 um 19 02 10" src="https://github.com/Isaksson/node-red-contrib-unifi/assets/63153849/62442b19-c7d7-4ed8-9d90-233887347251">
<img width="876" alt="Bildschirmfoto 2023-09-06 um 19 04 17" src="https://github.com/Isaksson/node-red-contrib-unifi/assets/63153849/5af879e0-162e-49ea-8031-70c4732da5b3">

**Comment by Isaksson** [comment]
There is no documentation because there is no official API, I could make an assumption and maybe get it right but I prefer to verify and test the code before I release it :) 

But I could make one new build and publish for you to test

**Comment by scarefirego** [comment]
If it doesn't bother you, I'd be happy to test it.
lets try. thx

**Comment by Isaksson** [comment]
In version 0.3.8 there is a new command that you use like this
`{ command: "setapledcolor", device_id: "24 char device id", color: "Color Hex code" }`

If you modify your AP and set anything else then Red in web interface then try the above command with Hex Code #ff0000 and let me know the result

**Comment by scarefirego** [comment]
perfect, it works fine. thank you very much. you helped me a lot

**Comment by Isaksson** [comment]
Great, have you tried with different HEX codes?

**Comment by scarefirego** [comment]
yes. thank you, all of hex codes :)

**Comment by scarefirego** [comment]
and now...the brightness? 



just a joke ;)
