### ISSUE TITLE
UDM Pro

### ISSUE THREAD

**Issue by chemicalmark35** [Isaksson/node-red-contrib-unifi#119]
Hi, Should this work on a UDMPro or is it just for software controllers?

**Comment by Isaksson** [comment]
Hello.
This works on UDM, so not only on older software versions.
But you need to have a local account and not only cloud user for this integration to work.

**Comment by chemicalmark35** [comment]
Thanks for your reply, I discovered that my issues were due to being a noob :) I have it working great now! Thanks
