### ISSUE TITLE
Cant Connect to Unifi

### ISSUE THREAD

**Issue by tompeel** [Isaksson/node-red-contrib-unifi#12]
So i have read all the other threads and still i cant get nodered unifi node to connect
its got a red square and says [object:Object] 
I have removed the site name, made another admin account with full access, double checked user and password.
Is there any chance its something to do with the httpS? unifi always throws an error when i go through its own ui in chrome do i want to proceeed ot unsecure page etc...
in the server field server i have tried http://, https:// and jsut the IP on its own but nothing seems to be working?

**Comment by Isaksson** [comment]
Have you tried the command "SiteStats" just to make sure that you use the correct site name? (when you run this command then the sitename in the configuration could be anything)
And it is also a great way to verify connectivity.
