### ISSUE TITLE
Enobufs error

### ISSUE THREAD

**Issue by hjuhlin** [Isaksson/node-red-contrib-unifi#121]
I have gotten a lot of enobufs (WSAENOBUFS) errors in Windows lately. After a lot of searching I did find a command (netstat -ab) to view open connections to find the problem. 

When running netstat -ab I did find out that node-red was the problem for all of my enobufs problems. And mostly Unifi connections (and some others). 

So I have MANY connections that are not closed to my UMD-Pro
[node.exe]  TCP    192.168.1.4:64755      unifi:https            ESTABLISHED

After running node-red for 12 hours I have around 2300 open connections in node-red and around 2/3 of them are to unifi. The other 1/3 are to Shelly components.

The command netstat -nao | find /i "estab" /c shows the total sum of connections that are established and that number just keeps growing until I restart node-red.

**Comment by hjuhlin** [comment]
Sorry, wrong Unifi node-red component! I'm using node-red-contrib-unifi-os. Sorry!

**Comment by Isaksson** [comment]
Ahh I see, no problem.

If this node has the functions you are requesting then fell free to change to this one instead :)

**Comment by hjuhlin** [comment]
I just did and it works perfect and have both health and client devices that are the functions I needed. Thanks! 🙏

**Comment by Isaksson** [comment]
Sound great 👍
I'm happy that you find this Node helpful.
