### ISSUE TITLE
Controller v8 support?

### ISSUE THREAD

**Issue by lubbergerc** [Isaksson/node-red-contrib-unifi#122]
Is controller v8 supported? The requirements say `Installed [UniFi-Controller](https://www.ubnt.com/download/unifi) version v4, v5, v6 or v7`. It would be good to know if we can update the controller without breaking existing automations which rely on node-red-contrib-unifi.

**Comment by Isaksson** [comment]
Hello.
I just updated my system to v8 and I have run some tests now and everything seems to be working just fine, so based on this test, there should not be any issues to update to v8.

**Comment by lubbergerc** [comment]
Thank you for running the tests. I've now also updated to v8 and can confirm that everything is still working as expected.
