### ISSUE TITLE
disablePoePort and enablePoePort not working on my US-8-150W

### ISSUE THREAD

**Issue by somebuddy87** [Isaksson/node-red-contrib-unifi#125]
i am not able to disable poe on a specific Port. 

I tried the following commands:

command: "enablePoePort", device_id: "xxxxxxx", port: "1", poe_mode: "off"
and
command: "disablePoePort", device_id: "xxxxxxx", port: "1"

both with no reaction or changed poe status. 

if i issue the command: getPoePortState on port 1 then the poe status remains unchanged on "auto".

**Comment by somebuddy87** [comment]
i tried the "hack" with enabling Storm Controll for my Port as mentioned in closed issue : https://github.com/Isaksson/node-red-contrib-unifi/issues/81#issue-1360939645

Then enabling POE and disabling POE is working.

**Comment by Isaksson** [comment]
Thanks for the information.
When I read the comments in that post it seems that I solved it in version 0.2.7, I will run some tests and see if the function is broken or if the "hack" still has be used for some models.

**Comment by Isaksson** [comment]
New version released with a fix for PoE, Let me know if this solves your issue.
