### ISSUE TITLE
SiteStats is only operable command, all others produce no output.

### ISSUE THREAD

**Issue by neurocis** [Isaksson/node-red-contrib-unifi#126]
UniFi controller version 8.0.28 from docker lscr.io/linuxserver/unifi-network-application
NodeRed version 3.1.3 from docker nodered/node-red w/ node-red-contrib-unifi version 0.3.13
Both containers running on bridge with their own assigned IP address

Command SiteStats produces accurate output, but no other commands do, nor any special commands. Node shows connection as "OK" and notice it cycles when running an "SiteStats" but does not show any visible activity with other commands. Option "Unifi OS" is unchecked. When "UniFi OS" is checked and "authetication failure" results.

Thanks.

**Comment by Isaksson** [comment]
Could you verify that you use your correct site name? the command SiteStats does not need any site name but the other commands does, you will find your site name in the output from the command SiteStats.

**Comment by neurocis** [comment]
Ugh, thanks. site name is 'default' although UI is set to single site and only visible name is my friendly name 'NeuroNet'. Working as expected now, issue can be closed.

**Comment by neurocis** [comment]
Closing.
