### ISSUE TITLE
New installation: default server port is 8443

### ISSUE THREAD

**Issue by jmorris644** [Isaksson/node-red-contrib-unifi#127]
I just installed for the first time and when initially setting up the server the port is filled in as 8443. I changed it to 443 and it started working.

**Comment by jmorris644** [comment]
Not sure if it part of the same issue, but UnifiWS will not connect. It attempts and I get nothing out of the debug to help analyze.

**Comment by Isaksson** [comment]
It's true, 8443 is the default in this node, I think it's time for me to change the default to 443, back when I created this node most installations of the controller was installed on servers and not on unifi hardware, then it was 8443 that was used.

Do you still have issue with the WS when you have changed your configuration to 443?

**Comment by jmorris644** [comment]
I had the WS node in the flow when I changed the port from 8443 to 443. It seems as if the WS node did not recognize the change.

I then deleted the WS node and put it back in. It is now connected but I am getting no data from it. edit: It seems that I did not wait long enough. I am receiving data.

**Comment by Isaksson** [comment]
Thanks for the info
