### ISSUE TITLE
 multi-factor authentication (MFA)

### ISSUE THREAD

**Issue by JosepFarreLlados** [Isaksson/node-red-contrib-unifi#133]
Hello, 
I just received a communication from Ubiquity Account Team as follows:

"
We wanted to extend a reminder that, beginning July 22, 2024, multi-factor authentication (MFA) will be mandatory for all accounts. You may choose an authentication method below, or visit [account.ui.com/security.](https://account.ui.com/security)

If you do not have an authentication method configured by the deadline, you will default to email authentication using the registered email on your account.
"

I'm looking the setup... Is possible use the multi-factor authentication?
![image](https://github.com/Isaksson/node-red-contrib-unifi/assets/98636450/ea183af7-8ad4-42f8-bfc9-fdf531bb8e7d)

Thanks in advance.

**Comment by Isaksson** [comment]
Hello.
This node will not be able to use MFA, MFA is only for access when a user login, not like this node, then there must be more like a service account login.
I don't think that they will force this on local access accounts, only on the cloud access accounts.

**Comment by JosepFarreLlados** [comment]
Hello Isaksson,
Many thanks for your reply!!
Currently I have at my local network running under docker container the following setup:

- [node-red v3.1.9](https://registry.hub.docker.com/r/nodered/node-red/)  
- [unifi 8.1.113](https://registry.hub.docker.com/r/jacobalberty/unifi/) 

I have followed the Unifi instructions and I set my unifi cloud account with (MFA).
Then I have tested access to unifi through my local network and is requested the MFA code. Also the unifi noder-red unifi node stops (previous to set the unifi MFA was working).

I'm looking at Unifi setup if I can setup a local user, but I can't find the way. It is possible?
Thanks in advance.
Best regards,

**Comment by Isaksson** [comment]
Hello.
There is a checkbox Restrict to local access only when adding admin to the Unifi system.
Then you could add username and password instead of email address.

This is image from Unifi Dream Router, maybe it looks different on other Unifi Console

![image](https://github.com/Isaksson/node-red-contrib-unifi/assets/4119080/d01f26f3-d200-42d0-b25f-f200d11dcb3b)

**Comment by JosepFarreLlados** [comment]
Hello Isaksson,
Many thanks for your reply!!
I'have a [switch USW-Lite-8-PoE](https://eu.store.ui.com/eu/en/collections/unifi-switching-utility-poe/products/usw-lite-8-poe) and I found that the switch has not and internal console with webserver and the unique way to control the switch is install a console on a computer and then communicate with the switch. Is correct?

In my case I'm using a docker container with the [unifi 8.1.113 console](https://registry.hub.docker.com/r/jacobalberty/unifi/) to control the switch. When I'm going to add a new user at my unifi container console I don't have the optinon to select only local acess... See my screenshots:
![image](https://github.com/Isaksson/node-red-contrib-unifi/assets/98636450/21304512-40d9-4c78-86ba-5c6cb21f0fcc)

![image](https://github.com/Isaksson/node-red-contrib-unifi/assets/98636450/43df6bdb-60d7-4d28-a9f1-8ec7971b95b6)

**Comment by Isaksson** [comment]
Yes, that is correct. You need to have a Controller (Console) installed to be able to mange the devices from this node.
If you uncheck the Remote Access, what happens then? it sounds like that would be the same as only local access.

**Comment by JosepFarreLlados** [comment]
Thanks for your reply [Isaksson](https://github.com/Isaksson)
I'have unchecked the Remote Access and it works, is the same as local access.
Let's close the issue.
Thanks!!
