### ISSUE TITLE
Set enablePoePort for multiple ports of a device 

### ISSUE THREAD

**Issue by JosepFarreLlados** [Isaksson/node-red-contrib-unifi#134]
Hello, 
This is not an issue, is a question related with the unifi syntax.
I would like to use "enablePoePort" command for multiple ports instead to send a "msg.payload" for each port.

I'have tested the following syntax and not works:
msg.payload = { command: "enablePoePort", device_id: "xx", port: **["1","2"]**, poe_mode: "off" };

Is possible turn on/off multiple ports of the same device using a single  "msg.payload" command?
Thanks in advance.
Best regards

**Comment by JosepFarreLlados** [comment]
solved, using:
msg.payload = { command: "setPortProfiles", device_id: "xx", port_overrides: [ {"port_idx": 1, "poe_mode": "off" }, {"port_idx": 2, "poe_mode": "off" } ] };

**Comment by Isaksson** [comment]
Great that you found the solution before I had the time to answer :)

**Comment by 877dev** [comment]
Is there a way to send `setPortProfiles` to multiple **devices** as well as multiple ports?

**Comment by JosepFarreLlados** [comment]
Yes, you can sent to multiple devices , following an example:
Turn on port 1 and 2: 

- msg1.payload = { command: "setPortProfiles", device_id: "xxx", port_overrides: [ {"port_idx": 1, "poe_mode": "auto" }, {"port_idx": 2, "poe_mode": "auto" } ] };

Turn off port 1 and 2:

- msg1.payload = { command: "setPortProfiles", device_id: "xxx", port_overrides: [ {"port_idx": 1, "poe_mode": "off" }, {"port_idx": 2, "poe_mode": "off" } ] };

**Comment by 877dev** [comment]
@JosepFarreLlados thanks for the reply, but unless I am missing something this is still only changing two ports on one device as before. I would like to change multiple ports on different devices.

E.g. turn poe_mode off for:
```
Port 1 on USW-150W switch 
Ports 3 & 4 on US-60W switch
```

Also is there a reason you use `msg1.payload` vs `msg.payload` ?

Thanks
