### ISSUE TITLE
Request treshold exceeded using "Offical Unifi Hosting" for a cloud key

### ISSUE THREAD

**Issue by Andr3asB** [Isaksson/node-red-contrib-unifi#136]
We're on the migration to the "Official Unifi Hosting" cloud key and see an error that says the flow exceeds the login attempt limit (see screenshot). So far, we operate about 40 sites within the cloud key. 

![image](https://github.com/user-attachments/assets/f75e4784-402f-418f-9fc2-d1491a61ea71)

The node should respect the request treshold or give the ability to handle this error within the flow properly on a second output.

**Comment by Isaksson** [comment]
I will take a look at this, but what do you receive in the output when this "error" occur?

**Comment by Nokomis449** [comment]
I've gotten this error also, but it's been a few months since the last time.  No consistency on frequency of occurrence - I have several sites running on various individual gateways (all on hardware, I have no cloud instances) and there was no explanation for when it would happen.  But once it happens, the flow continues to attempt a login every x minutes which (I suppose) prevents the failed login count to ever reset.  And I don't remember the node giving any output, it just seems to keep on trying with no obvious error except the text below the node.  A restart of Unifi software was the fix for me.

**Comment by Isaksson** [comment]
Ahh I see, the solution would be that this node blocks all incoming request to the node so that the node does not send any requests to the controller for x minute when this issue accrued? 
x = the official timer for the number of logins

**Comment by Isaksson** [comment]
I guess this is the "old" issue that the number of logins are limited not the actuals request when you are logged in, it seems like you are allowed to login 5 times and if you try to login the 6 time in a short period, maybe 1 minute, have not verified that yet, then the login will fail.

The login session will be reused within the node but not shared between the nodes, so I recommend to keep the number of nodes to the minimum when connected to the same Unifi controller to avoid this Unifi Controller limit.

![image](https://github.com/user-attachments/assets/2e684967-3b77-45fd-813e-2fdbd70061be)

**Comment by Nokomis449** [comment]
Good work, so it's neither a Unifi bug nor a flow bug.  Is there any way to catch the occurrence, so we can send the flow to a "wait"  for a specified time to clear the error?  Or maybe just check the output to see if it's empty?

**Comment by Isaksson** [comment]
Would you like a output so you will handle this with a wait node, or should this node have the logic and wait when this happens?
I am open for suggestions

**Comment by Nokomis449** [comment]
I personally think an output would be preferred and let the programmer determine the outcome.  Having it wait on its own could potentially stop the flow in cases where the programmer writes bad code.  What if the node had two separate outputs, one for "worked as expected" and one for "There was a problem"?

**Comment by Isaksson** [comment]
Sounds like a good idea.

**Comment by Isaksson** [comment]
What do you think about this, the node now has two output and when an error occur then the second output will send the same text that you will see on the node, this will be send on msg.payload

![image](https://github.com/user-attachments/assets/eb15d71e-cb32-4cf4-8d1e-f54d856ba0d9)
![image](https://github.com/user-attachments/assets/a4dd675a-0126-4704-848a-f6864378a9ea)

![image](https://github.com/user-attachments/assets/a16ed6f5-804f-4288-9fa5-142a840fe6f7)

**Comment by Nokomis449** [comment]
I think that will cover all the bases, current and future.
