### ISSUE TITLE
Trigger on interval

### ISSUE THREAD

**Issue by jolcese** [Isaksson/node-red-contrib-unifi#138]
Is it possible to control the frequency that calls to the Unifi controller are happening?
I understand I should be using a inject node with an interval but the UnifiWS node does not have an input port so it's triggered constantly

**Comment by jolcese** [comment]
I guess I was incorrectly connecting the UnifiWS -> Unifi which is not needed. I can now do the inject directly to the Unifi node and works.

**Comment by Isaksson** [comment]
Yes, you are correct.
If you just want to listen to events, like clients connect/disconnect/roaming and events like that then you could use the WS node, no need to poll that one, it will update as soon as the events happens.

The Unifi node needs to be triggered, then the node sends the selected command to the Unifi controller and returns the response.

**Comment by jolcese** [comment]
TY!
