### ISSUE TITLE
Trying to filter out the current rx rate for a client

### ISSUE THREAD

**Issue by adamrhoades** [Isaksson/node-red-contrib-unifi#14]
Good evening, 

I'm trying to create a flow that can tell me the current rx rate for a specific hostname so that I can monitor if its working/streaming content at all times.

I believe that I need to output the device.rx_bytes-r for the specific device, but I'm getting nowhere fast.

Can you assist me please?

**Comment by Isaksson** [comment]
Hello.
Could you show me your current flow so that I could see what you have made so far?
Then I could take a look at this tomorrow, it's very late here now.

**Comment by adamrhoades** [comment]
I've managed to get it working, but its far from elegant.

<img width="1468" alt="Screen Shot 2019-06-10 at 19 47 20" src="https://user-images.githubusercontent.com/570900/59218763-e42e6580-8bb8-11e9-9cd9-05016828e0f6.png">

My code looks like this:

> const client = {
>     "Adams-iPad": "Adams-iPad",
>     "amazon-04e1baafb": "amazon-04e1baafb"
> };
> 
> return Object.keys(client).map(function(topic) {
>     let devices = msg.payload[0].filter(device => device.hostname === client[topic]);
>     return {
>         topic: topic,
>         retain: true,
>         payload: devices
>     };
> });

I'm then relying on some extra nodes to get the data out including : 'JSONFilter' to get the rx_bytes-r & 'bigsplitter' to make it usable.

The rest of the flow checks if the rx rate has fallen below 500kbps (which would mean a cctv stream has stalled) If it stays consistently low for 5 consecutive checks, it sends a command to either reconnect in the case of an iPad, or Block and unblock in the case of a kindle fire. This is enough to kick start the stream again.

**Comment by eddy-weber** [comment]
hi, it would be possible that you could make the flow available. I would like to filter the active devices in my network, but I can not cope properly.

**Comment by Isaksson** [comment]
So, what do you say @adamrhoades will you share the flow?
