### ISSUE TITLE
enhancement request: Add/change/delete DNS server entries

### ISSUE THREAD

**Issue by jmorris644** [Isaksson/node-red-contrib-unifi#140]
This summer Unifi added the capability to add DNS entries like A records on the UDM Pro. I would like to be able to manage these via a node-red interface.

The GUI for this can be found under Settings/routing/DNS

Thanks

Joe

**Comment by Isaksson** [comment]
I will take a look at this.

**Comment by Isaksson** [comment]
I have published a new version that includes commands for Custom DNS

`getCustomDNS : Get array of Custom DNS entries { command: "getCustomDNS" }`

`setCustomDNS : Create new Custom DNS entry { command: "setCustomDNS", record_type: "A|AAAA|MX|TXT|SRV", value: "IP address|Text|Domain name", key: "Domain name", priority: 0-65535, weight: 0-65535, ttl: 1-86400, port: 1-65535, enabled: true|false, _id: "_id of current Custom DNS entry if you want to update" }`

Let me know if you need any help to get you started with this.

You find this in version 0.3.19

**Comment by jmorris644** [comment]
Something weird as I was trying to figure it out. I got the error  under the node "You've reached the login attempt limit" Then after a time I was able to work again.

**Comment by jmorris644** [comment]
Ah, I figured it out. I need to feed it JSON (not string) and the string I sued was 
```
{"command":"getCustomDNS"}
```

The quotes around the word command seems required.

**Comment by Isaksson** [comment]
Almost always, I use a Function node and in this case to get all the custom DNS this is what you should type in that node

`msg.payload = { command: "getCustomDNS" }
return msg;`

**Comment by jmorris644** [comment]
I keep getting the "You've reached the login attempt limit" response. Any idea what I can do to eliminate this?

BTW, thanks for adding the DNS code. It is working great!!

**Comment by Isaksson** [comment]
That is a new "feature" from Unifi, they block the login requests if it receives to many requests during a time frame.

I have made some tests but I don't have the results in front of me right now, but it's something like max 5 login requests during 1 minute.

I have built this node so it keeps the login cookie so the node does not need to login at every request, but if you use multiple of this node then each of them needs to login.

So maybe you use several of this node? And maybe you could reduce the number of node and send different commands to that node instead?
Let me know if this is the case.

**Comment by jmorris644** [comment]
I have been using a single node as I am have been working on manipulating the output.

So maybe the cookie is not working at the moment?

**Comment by Isaksson** [comment]
So if you make like 5 requests then you get that error and if you wait for a while then you could do another 5 requests?

**Comment by jmorris644** [comment]
I just did about 50 with no issue. so I am not sure what is actually causing it.

**Comment by Isaksson** [comment]
Then it works like it should, maybe you made changes and clicked deploy several times in a short time period? after a deploy the node makes a new login

**Comment by jmorris644** [comment]
Ah, that is exactly it then. I was doing a deploy after each change to test it.
