### ISSUE TITLE
Great project - small issue with UniFi

### ISSUE THREAD

**Issue by 877dev** [Isaksson/node-red-contrib-unifi#15]
Firstly thanks for the great project, very useful. I have it working great for host detection with the example in the "closed" issues.

One problem I am having is UniFi showing disconnected clients as still connected. I have raised this on the community page, but am interested if anyone has had that issue here?

Thanks!
877

**Comment by Isaksson** [comment]
Yes, that is an issue with Unifi and it has been like that forever now.
I have tried multiple times with the Unifi support but they does not think this is an issue.
The good thing is that its very responsive when clients connect, but could be like 10 minutes before it report that a client has disconnected.
I know several people that uses ping against the client instead to see if its still connected or not.

**Comment by 877dev** [comment]
Thanks for the information! 

Yes Ubiquiti do not seem so good at fixing things like this it seems. Mine also takes around 10mins to show disconnected. Pressing ‘reconnect’ next the client updates it immediately but I’m not sure it’s practical. 

I will look into ping’ing, I’m not sure if that is done via a specific ping node.  👍
