### ISSUE TITLE
no WAN2 status display

### ISSUE THREAD

**Issue by beccsjb** [Isaksson/node-red-contrib-unifi#16]
Hi, I cannot seem to find any reference of WAN2 in any of the health stats? 

Im needing to see data passing through WAN2, am i missing something? I can see WAN1 fine under health check.

**Comment by beccsjb** [comment]
Guessing this node is somewhat dead?

**Comment by 877dev** [comment]
Not dead but maybe not maintained?

**Comment by beccsjb** [comment]
> Not dead but maybe not maintained?

Certainly seems that way 877dev! Has anyone else been able to extract the WAN2 traffic via this node?

**Comment by Isaksson** [comment]
The problem here is that I do not use a USG as gateway, so I can't really test this issue.

**Comment by Isaksson** [comment]
And that I for some reason don't receive emails anymore from GitHub when someone posts here.

**Comment by beccsjb** [comment]
Doesnt seem to be emailing me either on updates it would seem.

You've done well to get thus far then!

The data is obviously pushed to the cloud key as its visible via the controller interface, but only individually. It would be nice to be able to push this data to nodered for analysis/monitoring is all.
