### ISSUE TITLE
authentication token required

### ISSUE THREAD

**Issue by simonlock** [Isaksson/node-red-contrib-unifi#17]
Would it be possible to add an option to allow entering the current authentication code alongside the controller's credentials? I'm cloud hosting my controller.

**Comment by Isaksson** [comment]
What is the "current authentication code" in this case? Unifi standard or something added by the cloud provider?

**Comment by simonlock** [comment]
2FA two factor authentication as offered by UniFi as standard.

**Comment by Isaksson** [comment]
Ahh I see, I have not tried that solution myself.
Do you host the controller in the cloud or do you have the controller in you network and then just use Unifi cloud for access from the outside?

**Comment by simonlock** [comment]
Hi Kristoffer

I host my controller in the cloud.

Regards

Simon

**Comment by simonlock** [comment]
I host my controller in the cloud but I have also enabled the UniFi cloud access for both my controller and UniFi-Video. The same 2FA code, which has been set up with UniFi, is used for both my controller and UniFi-video application.

**Comment by Isaksson** [comment]
When using 2FA then its not possible to use this Node, maybe if you could create a new account as a service account and then dont enable 2FA on that account, I dont know if that is possible when it comes to Unifi.
