### ISSUE TITLE
websocket

### ISSUE THREAD

**Issue by leifnel** [Isaksson/node-red-contrib-unifi#18]
Is it possible to use websocket to monitor real-time when a client connects/disconnects, and to which api?

The client display in unifi controller updates within a few seconds when a client connects/disconnects.

**Comment by 877cms** [comment]
I hope so. Mine shows clients quickly when connecting, but takes around 10 mins to show them as disconnected.

**Comment by Isaksson** [comment]
When a new client connects then you will see it direct but when a client disconnects that could stay as connected for several minutes.
So I still recommend to "ping" the actual clients to know if there still is online, not a good solution but this has been an issue with unifi from the very beginning and I have opened several cases with there support but they do not think that is an issue.
