### ISSUE TITLE
reboot access point

### ISSUE THREAD

**Issue by dfgas** [Isaksson/node-red-contrib-unifi#20]
is there a way to add rebooting the access point? when i block and unblock clients sometimes i have to reboot the ap for them to be able to reconnect.

**Comment by Isaksson** [comment]
I have now added this feature as a non-gui command.
you could restart an AP with this command

msg.payload = {command:"restartAP",mac:"device MAC address"};
return msg;

After you have received the update of the Node. (version 0.0.7)

**Comment by Isaksson** [comment]
Have you tried the new function?

**Comment by dfgas** [comment]
Sorry, it's been hectic at work with the virus. I will check it out this weekend

**Comment by dfgas** [comment]
ok, just tried it, it does reboot my AP. thank you very much.

**Comment by Isaksson** [comment]
I understand, thanks for testing this out.
