### ISSUE TITLE
Latest version does not work

### ISSUE THREAD

**Issue by Isaksson** [Isaksson/node-red-contrib-unifi#22]
When installing the latest version from NPM it does not work (nothing happens when running the node)
Installing it from local location with NPM Install location then it works.
Need to find a solution for this.

**Comment by rysiok** [comment]
Please change 1398 in unifi-helper.js from       
`function() { return count < proc_sites.length; },`
to
`function(cb) { 	cb(null, count < proc_sites.length); },`

**Comment by Isaksson** [comment]
> Please change 1398 in unifi-helper.js from
> `function() { return count < proc_sites.length; },`
> to
> `function(cb) { cb(null, count < proc_sites.length); },`

Thanks for the help.

**Comment by rysiok** [comment]
waiting for the release to test. I've tested with the latest async lib.

**Comment by Isaksson** [comment]
> waiting for the release to test. I've tested with the latest async lib.

New version published to NPM

**Comment by rysiok** [comment]
> > waiting for the release to test. I've tested with the latest async lib.
> 
> New version published to NPM

Resolved.
