### ISSUE TITLE
Commands not working with Unifi OS

### ISSUE THREAD

**Issue by Isaksson** [Isaksson/node-red-contrib-unifi#23]
This is a list with commands that needs to be modified for the new Unifi OS (UDM Pro)

- ~~AllUsers~~ Fixed in version 0.1.5
- DisableWlan

**Comment by patrick-dmxc** [comment]
DisableWLAN still Not work

**Comment by Isaksson** [comment]
> DisableWLAN still Not work

Thanks for testing, are you sure that you use the correct ID for the Wlan?

**Comment by patrick-dmxc** [comment]
Yes im sure, i copy paste the id from the wlanSettinds

i got a empty payload as result when send the command

**Comment by Isaksson** [comment]
> Yes im sure, i copy paste the id from the wlanSettinds
> 
> i got a empty payload as result when send the command

Do you sent the command as Boolean or String?, if you send it as string please try it like this.

`msg.payload = {command:"disableWLan",wlan_id:"0123456789abcdefghijklmn",disable:true};
return msg;`

**Comment by patrick-dmxc** [comment]
msgn={payload:""};
if(msg.payload==0)
msgn.payload = { command: "disableWLan", wlan_id: "5e753d57af47ee026f25745b", disable: true };
else
msgn.payload = { command: "disableWLan", wlan_id: "5e753d57af47ee026f25745b", disable: false };
return msgn;

**Comment by Isaksson** [comment]
> msgn={payload:""};
> if(msg.payload==0)
> msgn.payload = { command: "disableWLan", wlan_id: "5e753d57af47ee026f25745b", disable: true };
> else
> msgn.payload = { command: "disableWLan", wlan_id: "5e753d57af47ee026f25745b", disable: false };
> return msgn;

Then I guess there must be some bug with the UnifiOS or if they for some reason changed this part.
If I try to set same status as the Wlan already is then it looks like this.
![unifiwlan](https://user-images.githubusercontent.com/4119080/78985600-7f6dcf80-7b29-11ea-8117-d41ee737d9f6.PNG)

Thats is the closest empty payload that I could manage to get, but this is not against Unifi OS.

**Comment by chrislwade** [comment]
The fix for AllUser and BlockedUser is to use GET instead of POST.  It seems they've adjusted the `stat/alluser` endpoint to only respond to GET now.  I have confirmed this by creating the AllUser using normal HTTP request nodes and was able to get the expected response.

**Comment by Isaksson** [comment]
> The fix for AllUser and BlockedUser is to use GET instead of POST. It seems they've adjusted the `stat/alluser` endpoint to only respond to GET now. I have confirmed this by creating the AllUser using normal HTTP request nodes and was able to get the expected response.

Ah, thanks for the help.
It's hard to maintain this against a product you can't test against.

**Comment by Isaksson** [comment]
@chrislwade when you test the AllUser with GET don´t you send a json with type, conn and within?

**Comment by chrislwade** [comment]
You send them as query parameters now.

I can give you the subflow I'm using to replace this node for now if that would help?

**Comment by Isaksson** [comment]
Yes, that would be great, if you have verified that it works against UnifiOS then I could make the changes for this Node.

**Comment by chrislwade** [comment]
[flows.json.txt](https://github.com/Isaksson/node-red-contrib-unifi/files/4512145/flows.json.txt)
Let me know if you need anything else.  And yes, I'm running UniFi OS on my UDMP, fm 1.7.0rc8.

**Comment by Isaksson** [comment]
@chrislwade Could you test the new version 0.1.5, pushed it to NPM right now and see if AllUsers works now?

**Comment by chrislwade** [comment]
It looks like [flows](https://flows.nodered.org/node/node-red-contrib-unifi) site needs to be forced to update. Node-RED still shows 0.1.4 as the newest version available. [This](https://discourse.nodered.org/t/node-not-updated-in-palette-manager/10354) is what I found regarding how to do it.

**Comment by Isaksson** [comment]
> It looks like [flows](https://flows.nodered.org/node/node-red-contrib-unifi) site needs to be forced to update. Node-RED still shows 0.1.4 as the newest version available. [This](https://discourse.nodered.org/t/node-not-updated-in-palette-manager/10354) is what I found regarding how to do it.

I have now requested update, hope it solves the issue.

**Comment by chrislwade** [comment]
@Isaksson 0.1.5 fixes AllUsers for UniFi OS based controllers. Thank you!

**Comment by Isaksson** [comment]
> @Isaksson 0.1.5 fixes AllUsers for UniFi OS based controllers. Thank you!

Thanks for verifying this.
Have you noticed any other commands that does not work with UnifiOS? have you tried disableWlan? maybe same thing here, that they have changed method, it is PUT on older version.

**Comment by chrislwade** [comment]
Actually, I’m working on a PR that might fix a lot of commands. I noticed anything under `rest` needs a CSRF parsed from the JWT.

In theory though, at a minimum `blockedUsers` is broken in the same way. It’s likely that quite a few others are moving to more RESTful verbs as well.

I can try to test a few of them.

**Edit**: the change will simply parse the CSRF token on all possible calls to ensure it’s present if the controller wants it.

**Comment by chrislwade** [comment]
@Isaksson #29 adds CSRF support which likely fixes a number of commands against UniFi OS. This solution is very similar to the PHP [UniFi-API-Client](https://github.com/Art-of-WiFi/UniFi-API-client).

**Comment by chrislwade** [comment]
#30 should resolve `getBlockedUsers` as well.

**Comment by Isaksson** [comment]
@chrislwade  Thanks for the PRs.

**Comment by chrislwade** [comment]
@Isaksson did you publish 0.1.6 to npm? It doesn't look like it but I thought I'd ask.

**Comment by Isaksson** [comment]
> @Isaksson did you publish 0.1.6 to npm? It doesn't look like it but I thought I'd ask.

I have not, I had to run some test first but I will push it first thing tomorrow morning.
