### ISSUE TITLE
UDM-Pro - how to adress...?

### ISSUE THREAD

**Issue by schoebelh** [Isaksson/node-red-contrib-unifi#24]
Hi,
i migrated my controller yesterday to my new UDM-Pro. Now my nodered is unable to got the needed informations from the new instance. I updated the flow to version 0.1.2, set the checkbox for unifi-os und the site to "default" and Port to 443.
But i got everytime on the node "api.err.LoginRequired".

UDM-Pro has Version 1.6.6

Thank you for helping.

**Comment by Isaksson** [comment]
Hello.
It sounds that you have done the necessary modification.
Could it be some problems with the user that you are using for this?
Do you get the same error message if you enters incorrect login details?

**Comment by schoebelh** [comment]
Yes - same error with false login data. I tried alredy to use my unifi login, a local account added to this login in UDM-Pro and a complete separate local user i've added in UDM user management. No success.

**Comment by schoebelh** [comment]
Ok - solved the issue by complete uninstalling your flow and reinstall via palette. Dont know why updating from old version did not does the job.

Now its running against the UDM. Thanks for your work...!

**Comment by Isaksson** [comment]
Thanks for the information
