### ISSUE TITLE
Error on 1st attempt at using it

### ISSUE THREAD

**Issue by cymplecy** [Isaksson/node-red-contrib-unifi#33]
Using this
![image](https://user-images.githubusercontent.com/2357428/83510718-5f251600-a4c5-11ea-9f4a-72ba60612e18.png)

getiing this

![image](https://user-images.githubusercontent.com/2357428/83510778-7a902100-a4c5-11ea-9f9f-3a9868bbc45f.png)

https://discourse.nodered.org/t/node-red-contrib-unifi/27653

**Comment by Isaksson** [comment]
Are you sure that you get that error message when ju inject a timestamp? or could that error message be from a test you did with injecting commands (JSON)?

**Comment by cymplecy** [comment]
Pure timestamp as per image 1st attempt at using node ever -just installed it a few minutes beforehand - Windows10 if that makes any diff
Tried it twice - same error both times

**Comment by Isaksson** [comment]
Ok, then we will make a test like this.
1: inject node (timestamp is ok to use)
2: function node, add this code:
`msg.payload = { command: "events"};
return msg;`
3: your Unifi node
4: debug node

Please try this example.

**Comment by cymplecy** [comment]
That works fine

![image](https://user-images.githubusercontent.com/2357428/83514219-1d976980-a4cb-11ea-852a-1e5cfbe40e33.png)

**Comment by Isaksson** [comment]
Perfect.
I have made a change in the code and will publish that soon, I think that will solve your first Issue.
Do you need any more help about your first issue that you post on the forum, how to disable a AP?

you could to the same thing but replace the command and also add the MAC.
Change the code in the function node to this

`msg.payload = { command: "disableAP", mac: "device MAC address"}; return msg;`

**Comment by cymplecy** [comment]
"I have made a change in the code and will publish that soon, I think that will solve your first Issue"
Ta :)

**Comment by cymplecy** [comment]
"Do you need any more help about your first issue"

I've tried out your function code command and I get this error message

![image](https://user-images.githubusercontent.com/2357428/83516197-8e8c5080-a4ce-11ea-861a-67d925a43514.png)


JFI  I'm not the OP on that thread

**Comment by Isaksson** [comment]
Ahh I see, there is a change in the API.
I will correct this, the MAC is not the correct value to identify the AP, you need to use the 24 char device ID.
I will make the change to the code and update the Readme.

But the new function will be like this
`msg.payload = { command: "disableAP", device_id: "24 char device id"}; return msg;`

But that will be implemented in next version

**Comment by Isaksson** [comment]
> JFI I'm not the OP on that thread
Ahh I see, your just testing this out to help the OP.

I have now pushed the new version to NPM

**Comment by cymplecy** [comment]
I've upgraded to 0.1.11

![image](https://user-images.githubusercontent.com/2357428/83529156-e3859200-a4e1-11ea-9f5d-c277fe7e7bbf.png)


![image](https://user-images.githubusercontent.com/2357428/83528982-a7eac800-a4e1-11ea-86bf-1d9591916304.png)


Node shows red indicator and I get this in my console log

![image](https://user-images.githubusercontent.com/2357428/83529054-bc2ec500-a4e1-11ea-8025-a69d65d7b77e.png)

**Comment by Isaksson** [comment]
I will run some tests and see what is causing this error, the code was untested from my side.

**Comment by Isaksson** [comment]
Version 0.1.12 includes this fix

**Comment by cymplecy** [comment]
Sorry for delay - I (stupidly) decided to upgrade my controller from 4.x to 5.x and it was VERY wrong so I've had to re-setup my network!

Disable now works :)

![image](https://user-images.githubusercontent.com/2357428/83664111-777a5b00-a5c1-11ea-9d9c-c388d0d1f64b.png)

And enable works as well :)

![image](https://user-images.githubusercontent.com/2357428/83664254-a8f32680-a5c1-11ea-9b5c-1df49a594d00.png)


Thanks for your efforts :) - I'll report back to the forum :)

**Comment by cymplecy** [comment]
Just got another error when trying to inject timestamp into node to read accessdevices

![image](https://user-images.githubusercontent.com/2357428/83664646-29198c00-a5c2-11ea-9a59-f772db9aadb9.png)


![image](https://user-images.githubusercontent.com/2357428/83664695-3b93c580-a5c2-11ea-8a6c-ff9c4e9a382b.png)

I'd sucessfully done it once before so may just be a one-off glitch!

**Comment by Isaksson** [comment]
About your last error message.
From the error message I could read out that you are injecting the command disableap and it failes because its missing the parameter device_id

so maybe you inject a timestamp but it passes a function node that injects the command or something like that.

**Comment by cymplecy** [comment]
I "think" that the node seems to not handle direct timestamp injects consistently (based on other experiences I've had) but I'll wait till I can repeat the error before posting again

**Comment by Isaksson** [comment]
> I "think" that the node seems to not handle direct timestamp injects consistently (based on other experiences I've had) but I'll wait till I can repeat the error before posting again

There should no be any issues with injecting timestamp, you could inject anything, but if you inject a command then the payload must match that command.
So as long as you do not provide the command then it should be fine, and if you inject command then you need to make sure that you follow the information about the command from the Readme file.

**Comment by cymplecy** [comment]
OK -I've been thru all the options in the node just using timestamp as an injector and they all worked fine and without error :)

![image](https://user-images.githubusercontent.com/2357428/83689023-43fdf780-a5e6-11ea-987a-ca6431c38f57.png)

**Comment by cymplecy** [comment]
No error - but when I tried 1 (which sends msg.payload.command= "events" - I got events in debug

But then when I press plain timestamp into the node - it did events again even though node was set to AccessPoints

![image](https://user-images.githubusercontent.com/2357428/83689464-f8981900-a5e6-11ea-8a8f-a1f4c2e4f109.png)

**Comment by Isaksson** [comment]
> No error - but when I tried 1 (which sends msg.payload.command= "events" - I got events in debug
> 
> But then when I press plain timestamp into the node - it did events again even though node was set to AccessPoints
> 
> ![image](https://user-images.githubusercontent.com/2357428/83689464-f8981900-a5e6-11ea-8a8f-a1f4c2e4f109.png)

Ahh ok, but if you "deploy" between the tests then it works I guess.
In this case the Node remembers the last command and because of that it ignores the one from the drop down.
I will make a fix for this that will be included in next release (no need to push just the fix for this bug)

**Comment by cymplecy** [comment]
Manged to repeat the last error - I pressed 1 to disable the AP (which worked) and then press plain timestamp 2 which should have listed AccessDevices but instead gave the same error as last time

![image](https://user-images.githubusercontent.com/2357428/83690670-123a6000-a5e9-11ea-8bb3-7a59182b3ea7.png)

**Comment by Isaksson** [comment]
Yes, same thing.
It "remembers" the last command.

**Comment by cymplecy** [comment]
Could you publish the fix to NPM please?

**Comment by Isaksson** [comment]
> Could you publish the fix to NPM please?

Done.

**Comment by cymplecy** [comment]
The node is working fine for me on Version 0.1.13 - thanks for all your efforts :)
