### ISSUE TITLE
Is there a way to block/unblock LAN port?

### ISSUE THREAD

**Issue by 877dev** [Isaksson/node-red-contrib-unifi#34]
Hi @Isaksson 

Thanks for you continued work on this project, much appreciated. I am able to block MAC addresses, only problem my son discovered MAC change on his PC I think! :)

Is there a way to block/unblock LAN ports (switch8-150W) ?

Thanks

**Comment by Isaksson** [comment]
Hello.
I think the best solution here is to change the switch port profile.
I will need to make a function for that.

**Comment by 877dev** [comment]
That would be awesome, anything you can do is great!

**Comment by Isaksson** [comment]
Version 0.1.12 includes this new function.
You use it like this
`msg.payload = { command: "setPortprofile", device_id: "", profile_id: "", port_id: ""};`

device_id: the _id for the switch, you can find it using the command AccessDevices
profile_id: the _id for the profile that you want to set on that switch port, you can find it using the new command ListPortProfiles (You could use the default profile named Disabled)
port_id: the port number

Let me know if you have any questions.

**Comment by 877dev** [comment]
@Isaksson thank you, I have it working now!

I always forget that for the special commands,  it doesn't matter what is selected in the node 'command' drop down.

Here are the flows:
![image](https://user-images.githubusercontent.com/46575282/83664156-85c87700-a5c1-11ea-8325-6ad2bf7a36b8.png)


and here is the function:
![image](https://user-images.githubusercontent.com/46575282/83664343-c7f1b880-a5c1-11ea-9711-ab0adb639b23.png)

**Comment by 877dev** [comment]
@Isaksson ok I found an issue I'm afraid.

When I set the port 1 profile, it sets every other switch port profile to "All", and I lost all my port profile settings.


![image](https://user-images.githubusercontent.com/46575282/83665314-279c9380-a5c3-11ea-9993-9dcbe579c656.png)

**Comment by Isaksson** [comment]
> @Isaksson ok I found an issue I'm afraid.
> 
> When I set the port 1 profile, it sets every other switch port profile to "All", and I lost all my port profile settings.
> 
> ![image](https://user-images.githubusercontent.com/46575282/83665314-279c9380-a5c3-11ea-9993-9dcbe579c656.png)

How have you configured the other ports? have you set one by one a different profile or have you just added a profile for the switch?
I am just guessing now but if you have set one profile for the switch and then changing one port maybe the switch looses the first config because of the override that is used to reconfigure one port.

please try to modify port 2 by GUI to something else than All och den use the Node to set new profile on port 1 and see if it changes the port 2 again.

**Comment by Isaksson** [comment]
Ahh I think I know whats going on here, when I made this function I only tried on 1 port and all the other ports where on the default All.
When the Node injects the override it overwrite the current configuration for the override so if you have made custom changes to some other port that it will gets overwritten.
If it is like that, then its a little more complicated then the old configuration has to me fetched and then merged with the new configuration.

Well, sorry about your loss of configuration, but I guess you just have to reassign the correct profiles to the ports.

**Comment by 877dev** [comment]
@Isaksson it's no problem, I have a daily backup and just restored it.

If it's too much trouble I understand, sometime these things happen! :)

**Comment by Isaksson** [comment]
> @Isaksson it's no problem, I have a daily backup and just restored it.
> 
> If it's too much trouble I understand, sometime these things happen! :)

I have to think about this for a while to figure out the best approach.

**Comment by Isaksson** [comment]
My first approach, then I was thinking that the Node should connect and get current profile overrides on the switch and then add the one provided with this node, but then it would not be possible to delete an old profile on the switch from this node.
My second thought that I think is better, when sending the command from the node then include all the manual overrides that you want the switch to have, then it's possible to change several ports at the same time. The manual overrides will be provided by a json string.
What do you think about this solution?
I will also provide a simple command to read out the current overrides so that it will be simple to create the new json with the profiles.

**Comment by 877dev** [comment]
Hi @Isaksson that sounds good to me :)

> I will also provide a simple command to read out the current overrides so that it will be simple to create the new json with the profiles.

Anything like that would be great, it's not a major problem drilling down, but it would be nice to be able to find the profile ids & port id's more easily.

Thank you.

**Comment by wittekind** [comment]
Hi @Isaksson ,
I've offered a solution to the problem in the above pull request. I've tested it together with a function node, that first extracts the current `port_overrides` array. The user can then manipulate the fields, that need changing and pass it on to your node.
Find the gist of the extraction here: https://gist.github.com/wittekind/61690f3f8f8008d725a989d35faea5d0

**Comment by Isaksson** [comment]
I have now pushed the new version to NPM and also requested an update over at Node-RED.
Let me know when you have tested this @877dev  and thanks @wittekind for the PR

**Comment by 877dev** [comment]
After an embarrassingly long delay (life/not set notifications) I finally realised I forgot to test this out :/

Just had a go with the new command and it works great for changing profiles, friendly names and I assume PoE change. Can confirm it does not affect the other port profiles :)

Thanks to @wittekind and @Isaksson :)

(UDMPro running 6.2.25 Network)

Example functions for anyone like me who is not too good with formatting:

```
// Change a port profile

msg.payload = 
{
    command: "setPortProfiles",
    device_id: "60d23c53628b2dAAAAAA", 
    port_overrides: 
    [ 
        {
        "port_idx": 2, 
        "portconf_id": "5d7a9ba345d14f0AAAAAAA"
        }
    ]
};

return msg;
```

```
//Change a port friendly name

msg.payload = 
{
    command: "setPortProfiles",
    device_id: "60d23c53628b2dAAAAAAA", 
    port_overrides: 
    [ 
        {
        "port_idx": 2, 
        "name": "Hello"
        }
    ]
};

return msg;
```

```
//Change a port PoE status

msg.payload = 
{
    command: "setPortProfiles",
    device_id: "60d23c53628b2dAAAAAA", 
    port_overrides: 
    [ 
        {
        "port_idx": 2, 
        "poe_mode": "off"
        }
    ]
};

return msg;
```
