### ISSUE TITLE
Feature Request: Get switch port stats

### ISSUE THREAD

**Issue by jeroenst** [Isaksson/node-red-contrib-unifi#36]
I would like to get the stats of the uplink port of my switch to determine current load of the internet link.

Can this feature be added?

**Comment by jeroenst** [comment]
Found it in command AccessDevices.

**Comment by ozett** [comment]
i tried to get my switch-stats and send this command, but got an error.
maybe your are so kind to provide a sample flow here as an example (to copy?)
thanks.
