### ISSUE TITLE
Disable WLAN won't work

### ISSUE THREAD

**Issue by sbstn-0x2a** [Isaksson/node-red-contrib-unifi#40]
Hi.

I´m using Unifi Controller v 5.13.32 with your node 0.1.14 and nodered v 1.1.0

Unfortunally the command won't work and I don´t know why.:

![image](https://user-images.githubusercontent.com/35026880/86631554-90b26500-bfce-11ea-8a7d-9750e9f4a1e6.png)

![image](https://user-images.githubusercontent.com/35026880/86631607-a45dcb80-bfce-11ea-954e-0a62c6187617.png)

![image](https://user-images.githubusercontent.com/35026880/86631693-b9d2f580-bfce-11ea-9655-57654e140970.png)

![image](https://user-images.githubusercontent.com/35026880/86632246-6ca35380-bfcf-11ea-946c-b0ef1c3d5584.png)

ive checked the id twice, but nothing.
the wlan stays online.
node-red-log shows no error at all.

have you any tips?
thank you very much

**Comment by Isaksson** [comment]
Hello.
Please change in you command disabled to disable

**Comment by sbstn-0x2a** [comment]
Thank you very much.
It works now like a charm.
I haven't seen that typo for hours!

* facepalm * ^^
