### ISSUE TITLE
Using special commands not working

### ISSUE THREAD

**Issue by Dabbadoeber** [Isaksson/node-red-contrib-unifi#42]
i am trying to use the Special command to block / unblock a devices
but as soon as i use a special command the Unifi Node turns red.
if i use the GUI commands there is no problem.

i use this payload :

{"command":"blockClient","mac":"74:b5:ff:ae:f2:aa"}
{"command":"unblockClient","mac":"74:b5:87:ae:f2:0f"}

25-8-2020 15:59:26 node: 6fbcd343.7b1dec
msg.payload : Object
object
command: "unblockClient"
mac: "74:b5:87:ae:f2:0f"

what am i doing wrong ?

Unifi version : 5.13.32-13646-1
Node red is running in docker.
GUI commands do work, Node is green and Says Ok
Special commands Node is Red en has no text

**Comment by Isaksson** [comment]
Have you tried any other special commands?
