### ISSUE TITLE
Feature Request: set LED Color (on flex-hd)?

### ISSUE THREAD

**Issue by ozett** [Isaksson/node-red-contrib-unifi#43]
i found setting the led on/off is possible.
is it possible to set the color? On the unifi-gui i could set the led color for my flex-hd. maybe possible with node-red?

![image](https://user-images.githubusercontent.com/5937811/91652817-f2f18880-ea9a-11ea-99b7-35891fc56146.png)

**Comment by Isaksson** [comment]
I would like to add that function, but the problem is that I do not have an flex-hd so I can't find the correct command for this.

**Comment by ozett** [comment]
how can i help?
do you need a wireshark dump? or anything else? log?

**Comment by Alex-joomla** [comment]
As more APs are capable of this function, is it possible to add this?
