### ISSUE TITLE
Another can not connect post [object:Object]

### ISSUE THREAD

**Issue by hillbicks** [Isaksson/node-red-contrib-unifi#44]
Hey,

I hope someone here can help me. No matter what I try, I always get the [object Object] message.I've tried with sitename empty and just SitesStats and also with  

`msg.payload = { command: "SitesStats"}; return msg `

in a function before the unifi node. I've tested the password several times. The thing is, I don't even see the request in the server.log from unifi, even if I change the loglevel to debug, so it seems to me the request doesn't even reach the controller. ip address and port are also correct . Node Red is running as a docker instance and I can ping and ssh to the controller from inside the node red container. 

![image](https://user-images.githubusercontent.com/3480073/91999982-48e55b00-ed3d-11ea-94d5-d95c472137b3.png)

This is the entry from the flow.json of node red:
`{"id":"4b83155c.a3f5a4","type":"Unifi","z":"e0e6ffd9.5bbd3","name":"","ip":"172.16.39.50","port":8443,"site":"default","command":"10","unifios":false,"x":270,"y":1560,"wires":[["302c6cc7.34073c"]]}`

Any idea what I'm doing wrong here?

**Comment by Isaksson** [comment]
What do you mean by  "[object Object] message"?

**Comment by hillbicks** [comment]
Basically this is all I get. No message from the debug node. 

![image](https://user-images.githubusercontent.com/3480073/92144521-1d36a380-ee17-11ea-9ef7-a13073d2a548.png)

Like I said, no matter whether I inset the SitesStas command via function node or in the unifi node directly. As I understood it, the StieStats command should work even if the sitename is empty. As long as: 

- ip and port and correct and reachable from the node running node-red
- username and password are correct
- command SitesStats is used

This is where I'm stuck and I'm looking for hints what could be causing this. 

Thanks

**Comment by Isaksson** [comment]
Okey, what Unifi controller do you have and could you access it from your docker container?

**Comment by Ricardo-Miguel-Caldeira** [comment]
Same here... Can ping UDM-Pro from docker container. 0.1.15 Version UDM 5.14.22 / Firmware 1.8.0
Only shows [object Object] in node.status and no message at all.

Can read an error in nodered log in docker 
ERROR: Error: connect ECONNREFUSED 10.1.1.1:8443

**Comment by Isaksson** [comment]
If you have he UDM-Pro then you have to select the Unifi OS box.

**Comment by Ricardo-Miguel-Caldeira** [comment]
Unifi OS box does not make any difference... Has the same behavior and error messages.

**Comment by Isaksson** [comment]
> Unifi OS box does not make any difference... Has the same behavior and error messages.

Do you really use port 8443 on your UDM? Have you tested with 443?

**Comment by Ricardo-Miguel-Caldeira** [comment]
That was it... Port  443 worked... How we find/change this?
Thanks!

**Comment by Isaksson** [comment]
> That was it... Port 443 worked... How we find/change this?
> Thanks!

Great that it works.
I think its better to leave it as it is.
On Unifi OS the default port is 443 and on the other controllers it is 8443.

I will add this to the documentation.

**Comment by eibyer** [comment]
I have the same **object Object** message on a simple flow, controller version is 5.12.35.0

![image](https://user-images.githubusercontent.com/19540436/93917517-f229cc00-fcbf-11ea-8b1a-4d3af4140b38.png)

This is my configuration screen:
![image](https://user-images.githubusercontent.com/19540436/93917612-108fc780-fcc0-11ea-9f9d-77a8cfdc328a.png)

**Comment by Isaksson** [comment]
And your controller is not Unifi OS based? Like the UDM or UDM Pro?

**Comment by eibyer** [comment]
Not UDM or UDM Pro. Interestingly, I have an old 0.0..6 version of Unifi
node in another machine that is able to connect to the Unifi API without an
issue.

**Comment by bee-eater** [comment]
I have the same issue with an Cloud Key G2+. 
I tried every combination possible with UniFi OS and Ports. 
Any tips left?

[EDIT]
My bad... had the firewall block the connection between two networks.... 
Now its working again perfectly. For everyone interested the settings for UniFi Cloud Key G2+ are:
UniFi OS: NO
Port: 8443
