### ISSUE TITLE
Feature Request: Firewall Rules On/Off

### ISSUE THREAD

**Issue by Ricardo-Miguel-Caldeira** [Isaksson/node-red-contrib-unifi#45]
Any chance of implemienting a simple ON/OFF firewall rulles please? This would be very interesting...

rest/firewallrule | GET/PUT | User defined firewall rules. 

Thanks!

**Comment by Isaksson** [comment]
I would like to add that function, but the problem is that I do not have an USG so I can't find the correct command for this.

**Comment by ozett** [comment]
i have a USG... may i can provide some information?

**Comment by Ricardo-Miguel-Caldeira** [comment]
> I would like to add that function, but the problem is that I do not have an USG so I can't find the correct command for this.

I have a UDMP... Let me know if can I help!

**Comment by kgalilio** [comment]
This would be a great feature to have.
Currently the unifi controller can only block wireless clients. Several customers complained for the past one year, but no fix available yet to block wired clients.
If this unifi node can dynamically enable/disable firewall rules, it will solve our problem and enable us to activate a preset firewall rule to drop all traffic from/to a certain client.
I have UDM Pro. Please let me know if you would like me to provide any logs if it would help implementing this feature.

**Comment by Isaksson** [comment]
Thanks to you all that would like to provide help with logs and things like that.
It's very time consuming to send logs, read log, make the coding and then send the files for test and then new logs and same thing all over again for several days.

What I need is access to the controller and the permission to enable/disable firewall rules, and I understand if you guys don't want to give me that kind of access to your environment.
And even if I get access I could not promise that it's possible to do this enable/disable from this node.

Maybe someone has a Test environment with a UDM Pro?
Or same spare equipment that they could connect or send to me to use for this kind of development.

**Comment by ozett** [comment]
would still be great to trigger on/off with node-red. but my usg is in use everday.. 😢 

![image](https://user-images.githubusercontent.com/5937811/117112838-f0fa6a80-ad89-11eb-902b-488128d4ee02.png)

found some start:
https://help.ui.com/hc/en-us/articles/360005460813-UniFi-USG-Advanced-Policy-Based-Routing-

but cannot automate... 😢

**Comment by ozett** [comment]
[i gave this here ](https://www.reddit.com/r/homeassistant/comments/bptmay/how_to_enabledisable_firewall_rules_edgerouter/)a try with ssh and it looked somehow like success. 

(but that did not change the gui-button, was alway green ) 🧛 
![image](https://user-images.githubusercontent.com/5937811/117119757-ca8cfd00-ad92-11eb-9ecb-5aeee98b8458.png)


maybe someon can bring this into this module here?

ssh into the USG, do this cmd:     ```show firewall statistics```

![image](https://user-images.githubusercontent.com/5937811/117118779-80574c00-ad91-11eb-9ef8-382125d5e4e2.png)

disable == set disable

do cmd: 
```
configure && set firewall name GUEST_IN rule 2006 disable
```
do cmd: 
```
commit
save
```



![image](https://user-images.githubusercontent.com/5937811/117118013-83057180-ad90-11eb-9e3c-a4211e1d578d.png)

enable == delete disabled

do cmd: 
```
configure && set firewall name GUEST_IN rule 2006 enable
```
do cmd: 
```
commit
save
```


![image](https://user-images.githubusercontent.com/5937811/117118523-25bdf000-ad91-11eb-9e36-d9a4ba1c704f.png)

![image](https://user-images.githubusercontent.com/5937811/117119972-0b851180-ad93-11eb-951c-4f27fb8e6538.png)


🌹 
but the automation from node-red would be better... 😄 

does the api allow "disable/enable" ?
![image](https://user-images.githubusercontent.com/5937811/117124335-7e44bb80-ad98-11eb-86f7-51941f738b3c.png)
