### ISSUE TITLE
Feature Request: Site> Enable/Disable Status LED 

### ISSUE THREAD

**Issue by kgalilio** [Isaksson/node-red-contrib-unifi#48]
Would appreciate if an option is added to enable/disable site status LED.
Not sure about other controllers, but in UDM Pro, all Access Points have an option for controlling the status LED lights"

- Use site settings
- On
- Off

unifi controllers still lacks the option to set a schedule for the status LED. Having a site-wide status LED control makes it easy to implement a schedule within node-red.

**Comment by Isaksson** [comment]
So you want an option to set AP mode for the environment and not for each AP, is that correct?

**Comment by kgalilio** [comment]
> 
> 
> So you want an option to set AP mode for the environment and not for each AP, is that correct?

Yes please. Unifi controller already has this 'Site' option. So any AP that is configured to follow the site setting for the status LED lights will be controlled by one command.
I have 6 Access Points, and the unifi node didn't like 6 'setAPLed' commands firing simultaneously. Some APs did not receive the command and the node showed a red square. I had to add a delay to sequence the commands to make sure all of them get through.
Imagine someone doing this with 50 APs.

**Comment by Isaksson** [comment]
New command available true for on and false for off
`msg.payload = {"command": "setsiteled", "mode": true};
return msg;`

**Comment by kgalilio** [comment]
> 
> 
> New command available true for on and false for off
> `msg.payload = {"command": "setsiteled", "mode": true}; return msg;`

Perfect! It works like a charm 👍
