### ISSUE TITLE
Working Only SitesStats

### ISSUE THREAD

**Issue by alexsahka** [Isaksson/node-red-contrib-unifi#5]
CONTROLLER VERSION  5.5.24, working only SitesStats, rest of functions ending up with ERROR. 

![image](https://user-images.githubusercontent.com/7469537/35079410-2063df82-fbbc-11e7-97e5-945f90653519.png)

**Comment by Isaksson** [comment]
Hello.
Is there any special reason for you to use an old controller as 5.5.24?
Do you get any error message in the node.js log?

**Comment by alexsahka** [comment]
OK Updated the controller to 5.6.29, the same problem.
https://community.ubnt.com/t5/UniFi-Updates-Blog/UniFi-5-6-29-Stable-has-been-released/ba-p/2191996

**Comment by Isaksson** [comment]
Ok, then we have to find the problem in your environment, the module is working against that version, and it should also work against that old version that you used.

Do you have admin rights on the account that you use from the module?
Have you installed the latest version of this module? pushed the change today, then you should get the error message direct in the node status.

**Comment by alexsahka** [comment]
After updating this module I got this:
![image](https://user-images.githubusercontent.com/7469537/35124248-468a8104-fc5a-11e7-8acc-b9762593d1ea.png)
Yes, I do have admin rights used in the module.

**Comment by Isaksson** [comment]
It seems that you have entered the wrong site name in the module, do you use the default name or have you changed it?
Please verify that your site name is correct.

**Comment by alexsahka** [comment]
Yes the site name is correct, with SitesStats in the settings no errors, and I got some information from this module

**Comment by Isaksson** [comment]
The thing is that the command SiteStats works with invalid site name, so thats the reason that command works.
So still think that the issue here is that you are using the wrong site name, if you use the command SiteStats does the result there match the site name that you have entered in the module?

**Comment by alexsahka** [comment]
![image](https://user-images.githubusercontent.com/7469537/35141765-f9af395e-fcb0-11e7-9a5f-9f5de32889be.png)

![image](https://user-images.githubusercontent.com/7469537/35141786-0eb34f2a-fcb1-11e7-9b31-5a15229d9cbd.png)

![image](https://user-images.githubusercontent.com/7469537/35141858-53e2c5f8-fcb1-11e7-97f8-674f77b1b339.png)

**Comment by Isaksson** [comment]
Please look at the output from the command SiteStats from the module
![sitestats](https://user-images.githubusercontent.com/4119080/35142200-e2ed346c-fcfd-11e7-990e-3b3024aa3b5b.PNG)
![sitestatsdebug](https://user-images.githubusercontent.com/4119080/35142285-29fea688-fcfe-11e7-8802-17b38eb7c724.PNG)

Does the Name match your myhome?

**Comment by alexsahka** [comment]
![image](https://user-images.githubusercontent.com/7469537/35142472-410c7d28-fcb3-11e7-9858-05a38cbfc89b.png)

**Comment by Isaksson** [comment]
Then you should use the name default instead of myhome.
Please try that and get back to me when you have.

**Comment by alexsahka** [comment]
Changed to UniFi, and error is still there. It is see something like num_user, e.t.c

![image](https://user-images.githubusercontent.com/7469537/35204092-ac7a8eea-fee0-11e7-9364-0160f2763e0e.png)

**Comment by Isaksson** [comment]
In the module you should use the name default

**Comment by alexsahka** [comment]
After changing the site name to default, (not module name) everything is good now. No errors now.
Please add this to module description.

![image](https://user-images.githubusercontent.com/7469537/35208014-e7a5b2e6-fefa-11e7-8b58-ca232400d77d.png)

**Comment by Isaksson** [comment]
Yes, that's good.
Site in the configuration is the name of your Unifi Site. I will try to explain that in the readme.

**Comment by alexsahka** [comment]
My Site name in the Unifi controller is different than "default" but it doesn't matter, I think this is bug, when I try to mutch names I got an error, as soon I changed Site name in the NodeRed module to "default", everything becomes good and error free.
Here is my controller site name:

![image](https://user-images.githubusercontent.com/7469537/35208552-e9b2d746-fefd-11e7-9c40-e9c5741c62e0.png)

**Comment by Isaksson** [comment]
Well actually it is not different, the name you see is not the actual name that is in use behind the scenes.
The correct name is the name you get when you run the command.
But I will make this more clear in the information about this module.

**Comment by Luc3as** [comment]
Hello, 
regarding this issue, I would like to set site name from another input as calling command from function, I'm getting the same error NoSiteContext. 
![image](https://user-images.githubusercontent.com/6381468/40250329-3cb7fc1c-5ad6-11e8-9349-c3d2c4839fda.png)
I even tried to add  this to unifi.js but still no luck. 
```
 if (msg.payload.site != null) {
       site = msg.payload.site;
}
```

**Comment by Isaksson** [comment]
Hello @Luc3as 
I did not receive any notification, maybe because this issue is in solved state.
I have created a new issue at https://github.com/Isaksson/node-red-contrib-unifi/issues/7
The discussion will continue there.

**Comment by jeylites** [comment]
I have the same problem, can't get Node Red to talk to the controller despite having the right info.
![Screen Shot 2020-04-21 at 4 59 21 PM](https://user-images.githubusercontent.com/9190080/79930561-7674dc00-840e-11ea-8752-55c3aec3ed5f.png)

**Comment by Isaksson** [comment]
> I have the same problem, can't get Node Red to talk to the controller despite having the right info.
> ![Screen Shot 2020-04-21 at 4 59 21 PM](https://user-images.githubusercontent.com/9190080/79930561-7674dc00-840e-11ea-8752-55c3aec3ed5f.png)

The error message state that there is problem with the login. Maybe you have checked the checkbox for UnifiOS but you don't have a UDMPRO?

**Comment by jeylites** [comment]
Now it works, I unchecked Unifi Os. I'm using a USG
