### ISSUE TITLE
setPortProfiles keeps overwriting port_overrides

### ISSUE THREAD

**Issue by kgalilio** [Isaksson/node-red-contrib-unifi#50]
Hi,
What is the best way to implement setPortProfiles? I am trying to enable/disable a LAN port on my switch, but every time the setPortProfiles node is called, the port_overrides reverts to default!
I am only interested in changing one port, without disturbing any individual port overrides.

**Comment by Isaksson** [comment]
That's how it works.
You have to send all your changes every time you want to change one port.
So if you have modified port 1,2 and 3 and want to modify port 4 from the API then you have to send your changes for port 1-3 and also the new changes for port 4.
