### ISSUE TITLE
Unifi-OS / UDMP only works with empty "port" field, but node thinks it's missing

### ISSUE THREAD

**Issue by mariusbach** [Isaksson/node-red-contrib-unifi#51]
Hi, 
my question upfront: Could the code be changed such that the Unifi node accepts an empty port field?

The details:
I don't know enough to propose a pull request. I have a UDM pro and for any Unifi-node I put into node-red, I don't need to specify a port; just the IP address is enough. 

The problem is, that the node thinks it's missing the port and that for every deployment of changes I have to manually confirm that I want to deploy despite the "missing" info in the node.

I have tried all ports as mentioned here: [UniFi - Ports Used](https://help.ui.com/hc/en-us/articles/218506997-UniFi-Ports-Used)

Only 8843 will keep the node itself working, but its output (using the access-devices command) is empty. With any other port, its output is `[object Object]` below the node and no message is passed on.

Without a port set at all, it works as intended. The Unifi-OS box is checked on.

Thanks for considering!

**Comment by Isaksson** [comment]
Hello. Have you tried to use port 443?

**Comment by mariusbach** [comment]
I have not. But I did now and it works. Stupid enough not having tried this one.

Thanks!
