### ISSUE TITLE
Doesn't work with UDM (v1.8.3) and controller v6.0.41

### ISSUE THREAD

**Issue by michelesilla02** [Isaksson/node-red-contrib-unifi#53]
Can anyone else confirm that it doesn't work or am I disabled and can't make it work? 😂
After updating the UDM the node stopped working and reported an error
![image](https://user-images.githubusercontent.com/46810028/101751645-c94ff080-3ad0-11eb-9b43-cee6dde45ef0.png)

So I tried adding "/network" after the IP address of the UDM and then the node reported an OK message but still won't return a payload. I tried selecting UniFi OS but doesn't change anything
![image](https://user-images.githubusercontent.com/46810028/101752189-804c6c00-3ad1-11eb-83f0-666f925046d0.png)

**Comment by Isaksson** [comment]
Maybe with that update your UDM changed to UnifiOS.
remove /network
keep the Unifi OS checkbox selected
change port to 443

**Comment by michelesilla02** [comment]
Ok that worked. Thank you a lot
