### ISSUE TITLE
Block a client in UDM Pro?

### ISSUE THREAD

**Issue by mattenausohz** [Isaksson/node-red-contrib-unifi#55]
I am trying to block a client with "msg.payload = {command:"blockClient", mac:"72:f2:a6:..."}; return msg;

The node says: OK but the client is not clocked in my network....

Can anyone help please?

**Comment by mattenausohz** [comment]
When I check "Unifi OS" I am getting a red dot under the node when sending the command. When I uncheck this option it says "OK". But in both cases no luck. 

This is the debug output when it says "OK": 
msg.payload : array[0]
[ empty ]

**Comment by pluto202** [comment]
Same here.. Any idea how to connect to a UDM Pro? Just migrated from a USG to a UDM Pro and missing this node since then :-(

**Comment by Isaksson** [comment]
Have you changed the port to 443 in the node?

**Comment by pluto202** [comment]
You made my day @Isaksson !!!

That worked out. I changed the port to 443 and ticked the box for UniFi OS. After getting the new Device IDs of my APs I'm able to disable/enable them again. So for me your node works with Unifi Dream Machine Pro Version 1.8.6 and Unifi  Controller Version 6.0.43. 

Thanks again!
Regards
Andreas

**Comment by 877dev** [comment]
> Have you changed the port to 443 in the node?

Brilliant, worked for me after installing a new UDM-Pro (was port 8443).
Thank you!
