### ISSUE TITLE
Two-Factor Authentication

### ISSUE THREAD

**Issue by bkabela** [Isaksson/node-red-contrib-unifi#56]
Are there any plans to bring Two-Factor Authentication?

**Comment by Isaksson** [comment]
I don't see any way to support two factor authentication in this node, then it can't run automatic if the user need to verify each login.
Or did I misunderstood your request?

**Comment by bkabela** [comment]
Yeah, that does make sense. I was just hoping to find a way to connect openHAB to my Unifi controller in a more secure way.

**Comment by Isaksson** [comment]
I think the best you could do is to create a new user with a very complex password and only use that account for this node.
