### ISSUE TITLE
Login-Problems

### ISSUE THREAD

**Issue by KevinSzr** [Isaksson/node-red-contrib-unifi#58]
Hi,
probably not an "issue", but still a problem for me.

I am using a UniFi Controller 6.0.44 on a Synology NAS.
For the first test I started with SitesStats. I put in the IP, Port, Username and Password.

If I check "Unifi OS" I get the error api.err.LoginRequired, if I uncheck the box I get api.err.Invalid.

Using my browser I am able to access the controller using this IP, Port, User and Password.

I have no idea where to look.

Best regards,
Kevin

**Comment by 877dev** [comment]
@KevinSzr try port 443 worked for me..

**Comment by KevinSzr** [comment]
Great — That did solve my connectivity issue. Unfortunately I get no output result. It is either an undefined payload or an empty array depending on the chosen command.

**Comment by 877dev** [comment]
I had to tick UniFi OS box, but other than that not sure.

**Comment by KevinSzr** [comment]
Still undefined payload as the result For SitesStats.

**Comment by 877dev** [comment]
Same here, but I haven't read the help for a while as I don't use that function.
Maybe the API changed?

**Comment by KevinSzr** [comment]
What help are you referring to? Do you have recommendations for me how to proceed in solving this issue?

**Comment by 877dev** [comment]
I meant the main readme on GitHub. I already said I don't know 🤷‍♂️

**Comment by stonesrose** [comment]
I'm getting the same issue. payload is blank or undefined.

**Comment by Isaksson** [comment]
> I'm getting the same issue. payload is blank or undefined.

Have you tried to tick the Unifi OS checkbox and change the port to 443?
