### ISSUE TITLE
Request: Device connection managment

### ISSUE THREAD

**Issue by erikvg01** [Isaksson/node-red-contrib-unifi#6]
Really appreciate the effort so far, it works well and gives me much needed insight in to my environment.  I would love the ability to manage wireless clients.  Reconnecting a wireless device is my top priority, but if I could also disconnect, and authorize through this tool that would be amazing.

Thanks!

**Comment by Isaksson** [comment]
Could you explain a little more about the reconnect function that you want.
Is there a function that you today do from the unifi web gui?

**Comment by Isaksson** [comment]
Is this the functions that you need?

*Authorize a client device
*Unauthorize a client device
*Reconnect a client device
*Block a client device
*Unblock a client device

**Comment by erikvg01** [comment]
Precisely!

**Comment by Isaksson** [comment]
I have now pushed a new version to Git and NPM with the new functions available.
Please try the functions and get back to me if it works the way you need them to do.

**Comment by erikvg01** [comment]
Brilliant, I will test right away!

**Comment by erikvg01** [comment]
This appears to be working as expected.  Amazing that you turned it around so quickly.  Thank you so much!

**Comment by Isaksson** [comment]
Thanks for the feedback.
Glad you enjoy this module 👍
