### ISSUE TITLE
compatibility with Unifi controller v6.x

### ISSUE THREAD

**Issue by megahorst** [Isaksson/node-red-contrib-unifi#60]
Hello,
the requirements are saying that this node is comptible only with the controller versions v4 and v5.
Is ist possible to ad compatibiöity with v6.x?

**Comment by vinceHH** [comment]
Hello,

same request here.
With a controller on version v6.x, we get this error :  api.err.invalid

seems there is an issue in the login function

thanks !

**Comment by 877dev** [comment]
I'm using the latest controller with a UDMPro and it seems to be working ok, have you tried it?
