### ISSUE TITLE
Empty Payload with CloudKey+ Gen2 v 6.5.53

### ISSUE THREAD

**Issue by theArcher73** [Isaksson/node-red-contrib-unifi#61]
I tried to read the client-device information but get allways an empty payload back.
The node shows a green connection-bubble in the flow.

I activated the unifi-OS-checkbox, used port 8443 and the IP of the CloudKey.

Can you give me an hint where I can look to solve the Problem?

Thx,

Steffen

**Comment by Isaksson** [comment]
Hello.
Could you please send some print screens of your flow so that I could see how it looks.

**Comment by theArcher73** [comment]
Hi,

thanks for your support. But, when I try to attach an image (*.jpg, *.png, 5Kb/ 16kB sized) I get an exception here in Github --> Something went really wrong and we can't process that file.....
I put three images in my google-drive and post the links, sorry

https://drive.google.com/file/d/1-K84wYGW-iBXjOZ4ZgUkuq_rMTUe72E3/view?usp=sharing
https://drive.google.com/file/d/1-D82dd57mfFliL0jIG9J6ZqnuTinl6v_/view?usp=sharing
https://drive.google.com/file/d/1-kKSba7TU_7FZyQXIVjkXGwhkP-z_jgg/view?usp=sharing

The default site in the unifi-controller is named home.

Steffen

**Comment by Isaksson** [comment]
I think it would be good to first try to find the actual Unifi name for the Site, its not always that simple that Unifi uses the name that you have entered.
Just add a simple inject -> Unifi node and select  SitesStats as Command username and passwors does not need to be correct here but Server/port/UnifiOs needs to be set correct.

You will get a payload with the information about all your sites, including the name (this is the correct name for your site to use in this node)

And one more think, if I am not wrong the default port for Unifi OS is 443 not 8443

Please try this and get back with the result :)

**Comment by smort82** [comment]
I am also having the same issue on CloudKey+ Gen2 v 6.5.55. Empty payload always, also when trying SitesStats at port 443

**Comment by theArcher73** [comment]
Hi,

sorry, I had any trouble with other topics.

![unifi_err](https://user-images.githubusercontent.com/45237523/147579490-3dc6100f-269f-4dad-b989-c05dfb581ff2.png)

There is no other result, except that here in Github the upload of pictures is possible again. The IP ist the IP from the cloud-Key. 
(?)

USG 3P  --> 4.4.56.5449062
Cloud-Key (UnifiOS) --> 2.2.12
Network --> 6.5.55

Steffen

**Comment by Isaksson** [comment]
> I am also having the same issue on CloudKey+ Gen2 v 6.5.55. Empty payload always, also when trying SitesStats at port 443

Have you also ticked the Unifi OS checkbox?

**Comment by Isaksson** [comment]
> Hi,
> 
> sorry, I had any trouble with other topics.
> 
> ![unifi_err](https://user-images.githubusercontent.com/45237523/147579490-3dc6100f-269f-4dad-b989-c05dfb581ff2.png)
> 
> There is no other result, except that here in Github the upload of pictures is possible again. The IP ist the IP from the cloud-Key. (?)
> 
> USG 3P --> 4.4.56.5449062 Cloud-Key (UnifiOS) --> 2.2.12 Network --> 6.5.55
> 
> Steffen

Yes, that's correct, it should be the IP address of the cloud key.

**Comment by bruce3322** [comment]
> I think it would be good to first try to find the actual Unifi name for the Site, its not always that simple that Unifi uses the name that you have entered.

Thanks, this helped me with the same issue (aside from port 443 and unifi OS ticked too). The site "name" I see in the controller is actually the site description and not the name. The site name itself seems to be a randomly generated alphanumeric string.

**Comment by Isaksson** [comment]
Yeah I think it depends on what version you where on when created the site, and if you rename it or leave it by it default value.
my site name is actually default

**Comment by Kimovitzh** [comment]
<img width="1434" alt="Skærmbillede 2022-02-20 kl  11 28 53" src="https://user-images.githubusercontent.com/30301774/154838449-5e357c18-0038-490f-8e16-1a131b2ffa58.png">


I just get undefined, what am I doing wrong here?
I inject `msg.payload = {"site":"site name"}`

**Comment by Isaksson** [comment]
What happens if you just inject a date or time or something, and lets the command in the Node get executed, is it still empty payload?

**Comment by Kimovitzh** [comment]
> What happens if you just inject a date or time or something, and lets the command in the Node get executed, is it still empty payload?
<img width="1407" alt="Skærmbillede 2022-02-21 kl  20 23 54" src="https://user-images.githubusercontent.com/30301774/155015670-58208900-8206-4b1c-8068-f479e7e3d98a.png">
Like this?
If yes, I just gets what the debug shows.
