### ISSUE TITLE
List blocked devices

### ISSUE THREAD

**Issue by nate8199** [Isaksson/node-red-contrib-unifi#62]
I'm trying to figure out if I can see blocked devices somehow?
I realized once I blocked a device it disconnects it and will not show up with ClientDevices.
I don't see any other method to see that a MAC is blocked, besides tracking it myself in node-red once I toggle it.

**Comment by Isaksson** [comment]
If you use the command "AllUsers" then I think you will find also the blocked users, I will make a function to only list the blocked users, but please try with "AllUsers" until I have added the new function.

**Comment by nate8199** [comment]
Hey that works I think, atleast on devices I have blocked before.
I'm traveling so will look into it more once I am home.
Thank you
