### ISSUE TITLE
Unifi node return empty payload

### ISSUE THREAD

**Issue by Jozef73** [Isaksson/node-red-contrib-unifi#63]
Hi there,
I can't get success to get work node-red-contrib-unifi.
I tried what I could find on the web, but no help...
It returns empty payload, node itself shows OK stat.

Version 0.1.16.

Any advice please?

thank you
jozef 
![flow](https://user-images.githubusercontent.com/96684879/147406855-b0cd2dbf-744c-4fe6-88c6-2bc1cba124cb.png)
![payload](https://user-images.githubusercontent.com/96684879/147406880-c4263a3c-7abf-4e86-aa8c-f5d0e26b9cb8.png)

**Comment by Isaksson** [comment]
Hello.
What command have you selected in the Node?

**Comment by Jozef73** [comment]
Hello,

I actually tried several commands.
like you see here
![command](https://user-images.githubusercontent.com/96684879/147413821-43a18ab7-067f-484b-b479-71db792fe36f.png)

Not only from list, but also using inject node or function node, from samples on internet.
Seeing your post, also used port 443, but another error occured.
Posting only IP and port without user/pass on SitesStats, no return.

**Comment by Isaksson** [comment]
I see, the port should be what is used by the controller 8443 for older versions and 443 for Unifi OS, standard ports it's possible to change to different port also.

I don't know what controller you use but have you tried selecting the Unifi OS and change to port 443?

**Comment by Jozef73** [comment]
Thank you,
I'm using Dream Machine Pro, ver. 1.10.4.
Selecting the Unifi OS and change to port 443 helps, it can return payload with data.

Thanks again!

**Comment by Isaksson** [comment]
Great that it solved the issue.
