### ISSUE TITLE
Disable a port on a UniFi Switch?

### ISSUE THREAD

**Issue by curana** [Isaksson/node-red-contrib-unifi#64]
Hi,

Is it currently possible to disable a specific switch port with this node?

Thanks for your work!

**Comment by Isaksson** [comment]
Hello.
You could use this command to change the port profile.

setPortProfiles: Set overrides for multiple ports of a device { command: "setPortProfiles", device_id: "24 char device id", port_overrides: [ {"port_idx": 1, "portconf_id": "id of the port profile", "name": "friendly name of the port", "poe_mode": "off|auto" }, ... ] }

**Comment by curana** [comment]
Ok, I will try it this way.

Thank you!
