### ISSUE TITLE
hilfe bei command senden

### ISSUE THREAD

**Issue by liv-in-sky** [Isaksson/node-red-contrib-unifi#65]
würde gerne einen comand senden. z.b die led ausschalten oder den ap disablen. es kommt aber leider immer nur no command  unter der unifi node - die node funktioniert, wenn ich z.b. AccessDevices auswähle - dann werden meine ap's angezeigt -.

sieht dann so aus
![Image 2](https://user-images.githubusercontent.com/18462890/152127396-8c63f54a-340f-495f-9113-a9207e56d793.png)

die functions sind so definiert:
![Image 4](https://user-images.githubusercontent.com/18462890/152127764-7e2f7e1e-16a9-4faa-9c6d-a1c246286456.png)

![Image 3](https://user-images.githubusercontent.com/18462890/152127782-7c05b330-1b31-4b21-af6f-8487c457586d.png)

für hilfe wäre ich dankbar

**Comment by Isaksson** [comment]
Hello.
Could you please try with this simple command in a function node and see if you still gets the message "No Command".
And also, what version of this node are you running?

`msg.payload = { command: "ClientDevices"};
return msg;`

**Comment by liv-in-sky** [comment]
hi - thanx for your help


_from": "node-red-contrib-unifi@0.0.6",

the command you gave me works !!

![Image 13](https://user-images.githubusercontent.com/18462890/152164746-77654972-4f1a-4d9a-9238-52bac90f5b37.png)

**Comment by Isaksson** [comment]
Ahh I see, that is a very old version of the Node, I don't think that commands was implemented in that version.
latest version is 0.1.17 so please update the Node and try again.

**Comment by liv-in-sky** [comment]
I have made an update of the node - now it is working - thanx
