### ISSUE TITLE
Feature Request: Toggle PoE Status of a Port

### ISSUE THREAD

**Issue by reibuehl** [Isaksson/node-red-contrib-unifi#67]
It would be great to be able to toggle the PoE status of a port to reboot a hanging PoE powered device.

**Comment by ostat** [comment]
you can do that with the **setPortProfiles** command.

![image](https://user-images.githubusercontent.com/2128234/174190827-e0e55e0b-fc7e-4534-afe9-8c39a3cad142.png)

Function content is
```
//Change a port PoE status of Dome Camera
msg.payload = 
{
    command: "setPortProfiles",
    device_id: "<switch device id>", 
    port_overrides: 
    [ 
        {
            "port_idx": 12, 
            "poe_mode": "off"
        }
    ]
};

return msg;
```

There is more info here #34
