### ISSUE TITLE
Is there a way to control Traffic Management rules?

### ISSUE THREAD

**Issue by fmarkf** [Isaksson/node-red-contrib-unifi#76]
Hi! 
I'd like to be able to control Traffic Management rules from Node-Red.
Is there a way of doing it using this addon?
Thank you!

**Comment by Isaksson** [comment]
If you create some traffic Management Rule, will it be created as an firewall rule or is it separated?

**Comment by fmarkf** [comment]
It is separated. 
I have also tried using id from the Traffic Management rules webpage with command "enableFirewallRule", but it did not work.

**Comment by Isaksson** [comment]
I do not have access to a device that have this feature, so it's hard for me to try to implement a function for this.

**Comment by fmarkf** [comment]
> I do not have access to a device that have this feature, so it's hard for me to try to implement a function for this.

I understand and appreciate what you've already implemented. 

Please let me know if I can run any tests that could help.
I have Dream Machine (standard) running UniFi OS UDM 1.12.22 - Network 7.1.66.
Thanks.

**Comment by Isaksson** [comment]
I have now pushed a new version that let you enable/disable Traffic Management Rules.

**Comment by fmarkf** [comment]
Thank you very much! 
I tested it and it worked! 
UniFi OS UDM 1.12.38 -  Network 7.2.97

**Comment by Isaksson** [comment]
Thanks for verifying the new commands.
