### ISSUE TITLE
Node lacks support for Ubiquiti power strips and plugs

### ISSUE THREAD

**Issue by mbenson1** [Isaksson/node-red-contrib-unifi#78]
Suggest adding support for Ubiquiti power strips and plugs.

**Comment by mbenson1** [comment]
I forked your repository and added support on a new branch.  Would you like it back?

**Comment by Isaksson** [comment]
Hello.
Thanks for that, I am implementing your code with some changes and added error handling.
But i presume that you have verified that your code is working? I do not have any power strip och plug so I cant verify the function.

**Comment by Isaksson** [comment]
Added in version 0.2.1
