### ISSUE TITLE
disablePoePort not working

### ISSUE THREAD

**Issue by hjhasler** [Isaksson/node-red-contrib-unifi#81]
Thanks for that.
Yeah, disablePoePort is another story :) I dont think that actually worked with older version of this node, I have located the issue but to fix I need to rewrite/and rethink that function.

But, there is one "hack" that you could try.

On the switch that you want to disable the PoE port:
Login to the controller and click the switch and then Ports, select the port that you want this node to have the possibility to disable PoE on and click port profile override and enable storm control (do not modify the 0 values) click on Apply Changes.

Now, lets try to disable that PoE port from this Node, let me know the result.

_Originally posted by @Isaksson in https://github.com/Isaksson/node-red-contrib-unifi/issues/80#issuecomment-1236172307_

**Comment by hjhasler** [comment]
I tried your approach. But I can not activate "storm control" with empty values. Only zero is not possible. I would need to enter at least 100. But that way it does not work either.

**Comment by Isaksson** [comment]
Ahh okey, I just did the same on my controller and on that controller it worked (the storm control gets back to disabled) but it enabled the port to be changed from this Node.
It was meant to be a very temporary solution until I have fixed this issue, to bad it did not work.

**Comment by hjhasler** [comment]
I tried it your way... After enabling and confirming, it gets back to disabled. After that, I tried to switch the power off. Unfortunately without success... :-(

**Comment by Isaksson** [comment]
Lets try 0.2.7 and see if that solves the issue, I could turn off PoE on my switch ports with this version, but there is a lot of combinations of switch models and controller versions.

**Comment by hjhasler** [comment]
Nicly done! disablePoePort and enablePoePort, both functions work perfectly. Thank you!

By the way, I’m using the US-8-150W switch.
