### ISSUE TITLE
Fail to install 0.2.7

### ISSUE THREAD

**Issue by PowerZone21** [Isaksson/node-red-contrib-unifi#82]
Got this log when i tried to install 0.2.7

2022-09-03T23:57:01.257Z Install : node-red-contrib-unifi 0.2.7

2022-09-03T23:57:07.025Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-unifi@0.2.7
2022-09-03T23:57:27.569Z [out] + node-red-contrib-unifi@0.2.7
2022-09-03T23:57:27.569Z [out] updated 1 package in 19.186s
2022-09-03T23:57:27.611Z rc=0

**Comment by Isaksson** [comment]
Do you get anything else in the log? Don't really see any errors?
What version did you have installed before you tried 0.2.7?
What version of Node RED?

**Comment by PowerZone21** [comment]
All I did was upgraded from the last version (didnt notice witch, but it was the last), then i have yo restart node-red.
When it started up again, the Unifi node was gone.
And i got this message when i tried to reinstall

**Comment by Isaksson** [comment]
Maybe your did an update from version 0.1x?

When updating from version 0.1.x to 0.2.x

Use Node-Red Version 3.x.x and Nodejs >=14.18.0
Configuration Node is added, you need to create a new Unifi Server and then update the existing nodes to use the new configuration.

**Comment by PowerZone21** [comment]
I remember upgrading this for a cople of weeks ago, so im certain that i had version 0.2.something
But i also see that im running node-red 2.2.2
I will try to upgrade this too👍🏻

**Comment by Isaksson** [comment]
When you have updated your Node-RED then I am sure you can install this module again.

Please let me know how it goes.

**Comment by PowerZone21** [comment]
Hi,
Upgraded Node-red to 3.0.2 and the Unifi Node working like a dream :)

**Comment by Isaksson** [comment]
That's perfect 🙂
