### ISSUE TITLE
Problem with Custom Commands

### ISSUE THREAD

**Issue by DevMA99** [Isaksson/node-red-contrib-unifi#83]
Hallo,

first of all thank you for this great node!

In my environment, I have ab Problem.

The default commands working fine.

But I have a problem with a custom command:

The command 
`{     "command": "ClientDevices" }` works fine. But the POE-commands do not work.
For example, die payload `{"command":"getPoePortState","device_id":"myDevId","port":"1"}`
doesn't return a result. "nothing happens"

Is it a bug or a "Layer 8 Problem"?

My setup:
node red v3.0.2
node-red-contrib-unifi v0.2.7
unifi-controller v7.1.61

**Comment by Isaksson** [comment]
Hello.
Thanks for reporting this, I will run some tests and get back to you.
By the way, did this command work for you with older versions of this Node?

**Comment by DevMA99** [comment]
Thank you very much.

Sorry, but I only used v7+ of this node so far.

**Comment by Isaksson** [comment]
I have solved the issue and pushed a new version 0.2.8
This command present more information about the selected port, if its enabled, in use and power and things like that, but also more information that is not about PoE but I dont think that is any issue for you, just use the information that you need and ignore the rest.

Please let me know if this solves your issue.

**Comment by DevMA99** [comment]
Hello,

now I am getting the right response. Thank you for fixing the problem so fast!

in the next days, I will also check some other commands.

You can close the issue

**Comment by Isaksson** [comment]
Perfect, just raise a new issue if you find anything else that is not working as it should and I will do my best to fix the issue as soon as possible.
