### ISSUE TITLE
SSID Password

### ISSUE THREAD

**Issue by martijndierckx** [Isaksson/node-red-contrib-unifi#86]
Is there any way to change the password for a specific SSID?

**Comment by Isaksson** [comment]
It is not possible with current version but I will take a look at your request and probably I will add this function in next version.
I will keep you informed about this in this case.

**Comment by Isaksson** [comment]
I have pushed new version 0.2.9 that includes a new command
`msg.payload = { command: "setWLanPassword", wlan_id: "you can get the id from the command getWLanSettings", x_passphrase: "New Password"};
return msg;`

Please verify and get back to me if this solves your issue, or if you have any other questions.

**Comment by martijndierckx** [comment]
Wow that was quick! Works like a charm! Thanks!
