### ISSUE TITLE
Example flow of how it can work

### ISSUE THREAD

**Issue by nodecentral** [Isaksson/node-red-contrib-unifi#9]
Sorry, it’s not really an issue - other than my own inabilities :) 

To help me better understand what’s possible with the UniFi node , please could you share a few examples of some flows that I could import ? Ones which I could then just update with my UniFi contoller up and credentials ?

**Comment by Isaksson** [comment]
Hello.
Sure, i could create some flows, but its kinda unlikely that its something that you need in your environment.
maybe you have an ide of something that you need, then I could help you to accomplish that (if its possible with this node)

But i will add some flows that will get you started

**Comment by Isaksson** [comment]
Here is one example to check if a specific device is connected to the network, in the example we are looking for a client with the name "SonosZP123" with this you could trigger something when your mobile phone gets connected to your network.

`[{"id":"b350c7f.50f5b38","type":"inject","z":"e6e53dea.17c48","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":320,"y":440,"wires":[["36b5ad67.d83bd2"]]},{"id":"420218d.a86a3e8","type":"debug","z":"e6e53dea.17c48","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":830,"y":440,"wires":[]},{"id":"f938eeaf.09f17","type":"function","z":"e6e53dea.17c48","name":"Check for host","func":"var json = msg.payload[0];\n\nfor(var i = 0; i < json.length; i++) {\nvar obj = json[i];\nif (obj.hostname == 'SonosZP123') {\n//Found\nmsg.payload = true;\nreturn msg;\n} else {\n//Not found\nmsg.payload = false;\n}\n}\n\nreturn msg;","outputs":1,"noerr":0,"x":640,"y":440,"wires":[["420218d.a86a3e8"]]},{"id":"36b5ad67.d83bd2","type":"Unifi","z":"e6e53dea.17c48","name":"","ip":"","port":8443,"site":"default","command":"20","x":470,"y":440,"wires":[["f938eeaf.09f17"]]}]`

**Comment by nodecentral** [comment]
Hi , thanks so much.

First hurdle for me is that I imported your SonosZP123 example , I then updated the IP/username/password for my Controller in the UniFi node and then changed the device name in function and run it. 

First issue is that the UniFi node is reporting a red error of ‘api.err.Invalid’ ?

**Comment by nodecentral** [comment]
FYI - If I use an injection node and set it to send the following message (as a string) -  { site: "site name"}
As long as the UniFi node is set to SiteStats, it will turn the status to green and say OK.

**Comment by Isaksson** [comment]
In your unifi controller, do you use default site name?
Most of the issue is that the wrong site name is used.
The command sitestats works without site name.
Check the output of that command and then you will find the correct site name.
If you have created a site for example named Isaksson then the site name will not be Isaksson, the name is created by the controller and could be just random xcbvggft.

**Comment by Isaksson** [comment]
Have you checked so that you use the correct site name?

**Comment by nodecentral** [comment]
Hi, it looks like it was the site name, that was the problem, I can do a few things now. Thanks so much for your help/guidance. Do you have an other example flows that you use Which you can share ? Do you present anything in the dashboard ?

**Comment by nodecentral** [comment]
Hi,  by any chance would you know how to create a flow/function that could extract and sort all of the IP addresses that are being used on the UniFi Controler ?

**Comment by Isaksson** [comment]
Do you mean the IP address that are being used by all the connected clients? Or should it include address used by the ap and switches?

**Comment by nodecentral** [comment]
Hi, 

Many thanks for responding, sorry - Ive just found out that the UniFi controller can show that information  now.  (It must be new or Ive been blind to it for a while)

Do you have any cool dashboard examples that you can share ?

**Comment by Isaksson** [comment]
I do not have any Unifi info on my dashboard but if I would then I would show some basic info like how many connected clients, number of clients on specific access point, I would also display if there is any error notification.
Maybe something like that?

**Comment by nodecentral** [comment]
That sounds cool, it would be great to see a flow that processes all the information and then present a summary like you suggest on the dashboard . Currently all I can do is the basics ike search for a specific host name etc.

**Comment by Isaksson** [comment]
If you use the command `AccessDevices` then you will get all unifi devices that you have on that site in your controller, then you could find connected users in this variable `user-num_sta` and if you wanna know connected guests then you find them in `guest-num_sta`
If you just want to get a number of new alarms then you could use the command `SiteStats` and get the number from the variable `num_new_alarms`

I hope this could get you started

**Comment by nodecentral** [comment]
Thanks for that (I’m still learning but I’ll give them a try)

The other flow I really wanted was to create  flow that sends an alert/notifications when someone connects via the VPN.

Is there any chance you have that flow or something similar already ? 

If not would you be willing to help me create it ?

**Comment by Isaksson** [comment]
I do not have any USG, I use Edge Router but I will take a quick look and see if I could find an possible API for that. I guess you have the Security Gateway and that you use that for VPN server?

**Comment by nodecentral** [comment]
Hi thanks , yes that’s correct - I have the USG with the VPN element set up

**Comment by Isaksson** [comment]
Maybe the command ClientDevices could be useful here.
I could not test but I could easily get if a connected client is on WiFi or connected with Ethernet maybe a VPN user will be possible to locate also.
Please connect a client and then run the command ClientDevices and check in the result Array if you find something that is indicating that it is connected with VPN.

**Comment by nodecentral** [comment]
Just an update to say that SiteStats can tell me how many VPN user are connected , under health and the 4th object, what I can’t find is the name of the user who is connected, when they connected etc and get a flow to pull them all together ..

> remote_user_enabled: true
remote_user_num_active: 1
remote_user_num_inactive: 0
remote_user_rx_bytes: 804239
remote_user_rx_packets: 3355
remote_user_tx_bytes: 1543191
remote_user_tx_packets: 2990
site_to_site_enabled: false
status: "ok"
subsystem: "vpn"

**Comment by Isaksson** [comment]
Ahh perfect 👍
What is your next flow that you will build?
