### ISSUE TITLE
Just asking for help with what you say in the docs

### ISSUE THREAD

**Issue by Just-another-pleb** [Isaksson/node-red-contrib-unifi#90]
In the "docs" there is the line:
```
Installed [UniFi-Controller](https://www.ubnt.com/download/unifi) version v4, v5, v6 or v7
```

The key word for me is UniFi-Controller.
It isn't on the page.
Let alone `controller`.

Could you elaborate on what is needed?

**Comment by Isaksson** [comment]
Sure, if you run the software on your own hardware then you need the UniFi Network Application or if you buy a router with built in Application like Dream Machine or Dream Router(there is more hardware) then it's already installed on that hardware.

**Comment by Just-another-pleb** [comment]
Oh, I have been told the EDGE router is not in the same family so I am not sure I can really do it.

**Comment by Isaksson** [comment]
Yes, that is correct, the Edge series could not be managed by this Node.

**Comment by Just-another-pleb** [comment]
Sorry.   My mistake.
