### ISSUE TITLE
Unable to connect to US-8-60W

### ISSUE THREAD

**Issue by uli-rpi** [Isaksson/node-red-contrib-unifi#92]
I can not connect to my US-8-60W switch unfortunately.
The connection by user / password via putty works fine, but in the Unif node, i get alway an ECONNREFUSED error.

How to connect correctly?

**Comment by Isaksson** [comment]
Hello.
You cant connect directly to a device, this nodes connects to your Unifi Controller and fetch all information from the controller.

**Comment by uli-rpi** [comment]
ok, thx, i didn't realize that, now it works
