### ISSUE TITLE
gather blocking status of a device based on MAC address

### ISSUE THREAD

**Issue by pluto202** [Isaksson/node-red-contrib-unifi#93]
Maybe there is already a solution. I would like to gather the status of a device if it is blocked or not. I use the special command blockClient or unblockClient with the device MAC address and see then in the debug the status of the device. As it may happen that the devices is blocked via the UnifiGui, I do not get an update into may flow so I would like to regularly check the status or  monitor a change of the blocked: true/false attribute of a device based on a MAC address.  

Regards
Andreas

**Comment by Isaksson** [comment]
Hello.
If you use the command, AllBlockedUsers will you see the blocked devices there?

**Comment by pluto202** [comment]
Hi, when I use AllBlockedUsers I get an array with all connected clients back and I can’t find the attribute “blocked” in one of them.

Regards
Andreas

Von: Kristoffer Isaksson ***@***.***>
Datum: Sonntag, 25. Dezember 2022 um 18:34
An: Isaksson/node-red-contrib-unifi ***@***.***>
Cc: Andreas Schäfer ***@***.***>, Author ***@***.***>
Betreff: Re: [Isaksson/node-red-contrib-unifi] gather blocking status of a device based on MAC address (Issue #93)

Hello.
If you use the command, AllBlockedUsers will you see the blocked devices there?

**Comment by Isaksson** [comment]
A new version will go live on NPM that will fix your issue, then you will find the actual blocked clients with the command AllBlockedUsers

**Comment by pluto202** [comment]
Thanks a lot

Von: Kristoffer Isaksson ***@***.***>
Datum: Freitag, 30. Dezember 2022 um 22:26
An: Isaksson/node-red-contrib-unifi ***@***.***>
Cc: Andreas Schäfer ***@***.***>, Author ***@***.***>
Betreff: Re: [Isaksson/node-red-contrib-unifi] gather blocking status of a device based on MAC address (Issue #93)

A new version will go live on NPM that will fix your issue, then you will find the actual blocked clients with the command AllBlockedUsers

**Comment by pluto202** [comment]
Works as expected. Thanks for fixing

**Comment by Isaksson** [comment]
> Works as expected. Thanks for fixing

Thanks for verifying
