### ISSUE TITLE
disable Wlan

### ISSUE THREAD

**Issue by alexte19** [Isaksson/node-red-contrib-unifi#94]
Hi,

I use node red v3.0.2.
If I try to use the disableWlan command it does not work.
wlan ID is correct, because if I try it with setWLanPassword  it's working.

How can I disable the wlan via node red?

Regards
Alex

**Comment by Isaksson** [comment]
Hello.
I just verified this command and it worked for me, what is the exact command that you use and do you receive any output?

**Comment by alexte19** [comment]
Hi,
I use the following:
msg.payload.command = disableWlan
msg.payload.wlan_id = 6210146a3aa0f2038f8f1b00
msg.payload.disable = true

And writing this I found the issue.
msg.payload.disable was set as string, I changed it to boolean and now it's working.

**Comment by Isaksson** [comment]
Good that its working now.
