### ISSUE TITLE
SSL Errors?

### ISSUE THREAD

**Issue by snowbooch** [Isaksson/node-red-contrib-unifi#95]
Attempting to migrate my Node-Red env. (Docker, Synology) to 3.0.2 and the Unifi node will no longer connect.

Getting 'CERT_HAS_EXPIRED" error when trying to run commands beyond 'SIteStats'. Any ideas? Thanks!

**Comment by Isaksson** [comment]
Could it be that you have "checked" the SSL Verification checkbox in the configuration for this node?

**Comment by pluto202** [comment]
I had also issues after this migration. Problem was, that the configuration of the Unifi node was not proper transferred. I had the change the port back to 443 and then all worked again.

**Comment by pluto202** [comment]
I had also issues after this migration. Problem was, that the configuration of the Unifi node was not proper transferred. I had the change the port back to 443 and then all worked again.

**Comment by Isaksson** [comment]
What kind of migration did you do to cause that issue @pluto202

**Comment by pluto202** [comment]
I updated my ioBroker environment to an actual version and as part of it got from Node Red 2.x to 3.0.2

**Comment by Isaksson** [comment]
> I updated my ioBroker environment to an actual version and as part of it got from Node Red 2.x to 3.0.2

And the only thing that changed was that your port was changed in the configuration of this node?

**Comment by snowbooch** [comment]
Thank you both for your quick responses.

Per your input, pluto, I deleted the configuration node, readded it, rekeyed (443), and now it works. Thanks!

**Comment by Isaksson** [comment]
What version of Node-Red was you running before the update to 3.0.2? was you using the latest version of this node before you started the migration?

Anyway, good that your node is up and running again :)

**Comment by pluto202** [comment]
I have to admit I don't know what my starting point was :-) I did not touch the complete environment for a while (around 1,5 years) and brought now everything to an actual version.
