### ISSUE TITLE
Documentation lacks working examples

### ISSUE THREAD

**Issue by rekcodocker** [Isaksson/node-red-contrib-unifi#96]
It would be a lot easier to start if the documentation contained working examples.
By that I mean _copy-paste and it works._ 
Not: The command is SitesStats.
So, do I set the message payload to the string 'SitesStats'?  A JSON?   Any parameters needed? What is the return value? 

Having a few working copy-paste examples can skip a lot of trial, error and assumptions.

**Comment by Isaksson** [comment]
You are right, some examples could be good to have.
There is two examples prepared in the example folder, one for regular command and one for special command.
But sure, I could add more examples.
