### ISSUE TITLE
setWLanPassword command not working :( 

### ISSUE THREAD

**Issue by MHagreis** [Isaksson/node-red-contrib-unifi#98]
msg.payload.command = setWLanPassword, wlan_id: My-Test x_passphrase: Newpassword

msg.payload.command = setWLanPassword, wlan_id: "My-Test" x_passphrase: "Newpassword"

What am i doing wrong node gives back No Command read works perfect and account is able to write to UNIFI DreamMachine

![image](https://user-images.githubusercontent.com/50264856/211152378-be25d728-8e7c-4cde-b105-c1c8e294bea8.png)

**Comment by ozett** [comment]
just a guess, (i am not using this),
but may you must use curly- brackets`{}` and set payload-type to JSON

![image](https://user-images.githubusercontent.com/5937811/211154382-6ad45d88-483f-4807-9ba8-28bb72bf8007.png)

**Comment by Isaksson** [comment]
use this in a function node
`msg.payload = { command: "setWLanPassword", wlan_id: "you can get the id from the command getWLanSettings", x_passphrase: "New Password"}; return msg;`

**Comment by MHagreis** [comment]
this works perfect thanks problem was is the wlanID this is the last part of the URL in the Unifi controller if you select the WIFI settings in the Unifi controller

thanks or putting me in the right direction now node red can create a password set this to guest wifi and create a QR code to scan :-) solved all my challenges thanks

**Comment by Isaksson** [comment]
That sounds great 👍
