### ISSUE TITLE
Block client requires reboot of USG router to restore internet access

### ISSUE THREAD

**Issue by rekcodocker** [Isaksson/node-red-contrib-unifi#99]
When I block a client and leave it blocked for a while, I can unblock it - but it does not get internet access anymore.  
The device IS connected again to the wifi but it does not get internet access.
I need to restart the USG-3P (router) to restore internet access to that device.

It happens when the device has been offline for a considerable time. just block-unblock will not cause this to occur.

**Comment by Isaksson** [comment]
If you block a client from the web gui will the result be the same?
I guess so but please verify.

**Comment by rekcodocker** [comment]
I'll check.
